/** Types for SC Monday customer demo bridge payload (read-only). */

export type ScCustomerDemoRow = {
  profile_id: string;
  recognition_type: string;
  grant_id: string;
  opportunity_title: string;
  funding_geography: string;
  data_label: string;
  live_ingest_not_claimed: boolean;
  classification_label: string;
  match_readiness_label: string;
  discoverability: string;
  confidence: string;
  missing_data: string[];
  blockers: string[];
  operator_next_check: string[];
  provenance_evidence_notes: string[];
  human_review_required: boolean;
  final_eligibility_claim_allowed: boolean;
  confirm_active_round?: boolean;
  excluded_from_match_set?: boolean;
};

export type ScCustomerDemoPayload = {
  schema_version: string;
  title: string;
  demo_route_path: string;
  demo_dev_only: boolean;
  offline_only: boolean;
  read_only_advisory: boolean;
  live_ingestion: boolean;
  source_activation: boolean;
  external_urls_used: boolean;
  auth_required: boolean;
  final_eligibility_claim_allowed: boolean;
  pack_id: string;
  capture_date: string;
  content_digest: string;
  claim_matrix: Record<string, unknown>;
  profiles: {
    profile_count: number;
    federal_recognized_count: number;
    state_only_count: number;
    fixture_keys: string[];
  };
  opportunities: {
    total: number;
    south_carolina_count: number;
    federal_count: number;
    by_data_label: Record<string, number>;
    opportunity_ids: string[];
  };
  classify_match: Record<string, unknown>;
  combined_summary: {
    row_count: number;
    south_carolina_row_count: number;
    federal_row_count: number;
    human_review_required_count: number;
    confidence_distribution: Record<string, number>;
  };
  missing_data_summary: {
    rows_with_missing_data: number;
    hidden_missing_data: boolean;
  };
  provenance_evidence_summary: {
    notes_visible: boolean;
    pack_evidence_required: boolean;
  };
  what_nativeforge_did: string[];
  what_requires_attention: string[];
  why_this_matters?: string[];
  workload_reduction_statement?: string;
  next_actions: string[];
  rows: ScCustomerDemoRow[];
  row_sample_note?: string;
  ui_flags: {
    show_activation_controls: boolean;
    show_submit_controls: boolean;
    advisory_banner: string;
  };
  buyer_demo?: {
    schema_version: string;
    demo_route_path: string;
    opening_line: string;
    closing_line: string;
    required_story_labels: string[];
    allowed_claims: string[];
    forbidden_claims: string[];
    trust_cues_required?: string[];
    claim_matrix?: Record<string, string>;
    live_ingest_claimed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    proposal_drafting_claimed: boolean;
    final_eligibility_claim_allowed: boolean;
  };
  opportunity_engine?: {
    schema_version: string;
    campaign_block: number;
    block_name: string;
    live_ingest_claimed: boolean;
    source_activation_claimed: boolean;
    final_eligibility_claim_allowed: boolean;
    buyer_summary: string[];
    sc_state_adapter: Record<string, unknown>;
    combined_workflow: {
      counts: Record<string, number>;
      organization_geography_filters_federal: boolean;
      missing_data_summary: Record<string, unknown>;
      human_review: Record<string, unknown>;
      eligibility_readiness_handoff: Record<string, unknown>;
      eligibility_evidence_handoff?: {
        pair_count?: number;
        federal_pairs_visible?: boolean;
        final_eligibility_claimed?: boolean;
        scoring_math_changed?: boolean;
        human_review_required?: boolean;
        sample_pairs?: Array<Record<string, unknown>>;
      };
      provenance_summary: Record<string, unknown>;
      combined_ordering_sample: Array<Record<string, unknown>>;
      next_checks_sample: string[];
    };
  };
  pursuit_workspace?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    final_submission_allowed: boolean;
    submission_ready_claimed: boolean;
    proposal_drafting_claimed: boolean;
    live_ingest_claimed: boolean;
    scoring_math_changed: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      workspace: {
        pursuit_workspace_id: string;
        opportunity_id: string;
        organization_profile_id: string;
        opportunity_source_layer: string;
        readiness_status: string;
        pursuit_status: string;
        missing_information_summary: string[];
        human_review_required: boolean;
        operator_next_actions: string[];
        customer_next_actions: string[];
        why_worth_review?: string;
        final_submission_allowed: boolean;
        submission_ready_claimed: boolean;
        proposal_drafting_claimed: boolean;
        not_submission_ready_label?: boolean;
        what_nativeforge_prebuilt?: string[];
        what_customer_must_provide?: string[];
      };
      evidence_binder: {
        item_count: number;
        missing_or_needs_confirmation_ids: string[];
        human_review_required: boolean;
        proposal_drafting_claimed: boolean;
        submission_ready_claimed: boolean;
      };
      readiness: {
        readiness_status: string;
        not_submission_ready: boolean;
        operator_next_actions: string[];
        customer_next_actions: string[];
      };
      application_plan_summary?: Record<string, unknown>;
      nofo_intelligence_present?: boolean;
    }>;
  };
  application_plan_workspace?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    submission_allowed: boolean;
    submission_ready_claimed: boolean;
    proposal_drafting_claimed: boolean;
    application_complete_claimed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    live_ingest_claimed: boolean;
    scoring_math_changed: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      application_workspace: {
        application_workspace_id: string;
        pursuit_workspace_id: string;
        opportunity_id: string;
        organization_profile_id: string;
        section_count: number;
        item_count: number;
        checklist_sections: Array<{ section_id: string; title: string }>;
        checklist_items: Array<{
          item_id: string;
          section_id: string;
          label: string;
          item_status: string;
          what_nativeforge_knows?: string;
          what_is_missing?: string[];
          next_action?: string;
          required_human_review?: boolean;
          unsupported_claim_guard?: boolean;
        }>;
        submission_allowed: boolean;
        why_submission_not_allowed?: string;
      };
      questionnaire: {
        question_count: number;
        questions: Array<{
          question_id: string;
          group: string;
          prompt: string;
          answer: null;
        }>;
        customer_next_actions?: string[];
        operator_next_actions?: string[];
      };
      opportunity_id: string;
      organization_profile_id: string;
      opportunity_source_layer: string;
      incomplete_item_count: number;
      question_count: number;
      what_nativeforge_knows?: string[];
      what_customer_must_provide?: string[];
      what_requires_human_review?: string[];
      why_submission_not_allowed?: string;
      unsupported_claims?: string[];
      submission_allowed: boolean;
      proposal_drafting_claimed: boolean;
      application_complete_claimed: boolean;
    }>;
  };
  intake_approval_workspace?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    binary_upload_persistence_supported: boolean;
    binary_upload_persistence_claimed: boolean;
    approval_persistence_supported: boolean;
    approval_persistence_claimed: boolean;
    submission_allowed: boolean;
    submission_ready_claimed: boolean;
    proposal_drafting_claimed: boolean;
    package_readiness_unlocked: boolean;
    live_ingest_claimed: boolean;
    scoring_math_changed: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      application_workspace_id: string;
      pursuit_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      opportunity_source_layer: string;
      intake_item_count: number;
      approval_count: number;
      open_approval_count: number;
      customer_must_provide: string[];
      operator_must_verify: string[];
      required_reviewer_roles: string[];
      what_remains_blocked: string[];
      why_package_not_ready: string;
      binary_upload_persistence_supported: boolean;
      binary_upload_persistence_claimed: boolean;
      approval_persistence_supported: boolean;
      approval_persistence_claimed: boolean;
      submission_allowed: boolean;
      submission_ready_claimed: boolean;
      proposal_drafting_claimed: boolean;
      package_readiness_unlocked: boolean;
      intake_plan: {
        intake_items: Array<{
          intake_item_id: string;
          intake_type: string;
          item_label: string;
          current_status: string;
          accepted_evidence_types: string[];
          customer_action_required: boolean;
          operator_action_required: boolean;
          approval_status: string;
          why_it_matters?: string;
          what_remains_blocked?: string;
          source_checklist_section?: string;
        }>;
      };
      approval_workflow: {
        approvals: Array<{
          approval_id: string;
          approval_type: string;
          required_reviewer_role: string;
          approval_status: string;
          cannot_unlock_reason?: string;
        }>;
      };
    }>;
  };
  narrative_budget_scaffold?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    drafting_supported: boolean;
    generated_prose_produced: boolean;
    proposal_drafting_claimed: boolean;
    budget_claimed_complete: boolean;
    match_claimed_complete: boolean;
    live_ingest_claimed: boolean;
    scoring_math_changed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      application_workspace_id: string;
      pursuit_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      opportunity_source_layer: string;
      section_count: number;
      customer_questions: string[];
      operator_checks: string[];
      budget_customer_questions: string[];
      drafting_supported: boolean;
      generated_prose_produced: boolean;
      proposal_drafting_claimed: boolean;
      budget_claimed_complete: boolean;
      match_claimed_complete: boolean;
      why_drafting_not_supported: string;
      narrative_scaffold: {
        sections: Array<{
          section_id: string;
          section_label: string;
          section_type: string;
          section_required_status: string;
          known_evidence: string[];
          missing_evidence: string[];
          question_prompts: string[];
          drafting_supported: boolean;
          generated_prose: null;
          unsupported_claim_guard?: boolean;
        }>;
      };
      budget_match_evidence: {
        budget_required_status: string;
        match_required_status: string;
        cost_share_required_status: string;
        amount_requested_known: boolean;
        match_amount_known: boolean;
        missing_budget_facts: string[];
        customer_questions: string[];
        budget_claimed_complete: boolean;
        match_claimed_complete: boolean;
      };
    }>;
  };
  package_readiness_queue?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    submission_ready_claimed: boolean;
    final_eligibility_claimed: boolean;
    proposal_drafting_claimed: boolean;
    live_ingest_claimed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    scoring_math_changed: boolean;
    not_submission_ready_label: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      application_workspace_id: string;
      pursuit_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      opportunity_source_layer: string;
      overall_readiness_status: string;
      blocked_reasons: string[];
      missing_information_count: number;
      human_review_count: number;
      unsupported_capability_count: number;
      next_safest_action: string;
      customer_next_actions: string[];
      operator_next_actions: string[];
      review_item_count: number;
      critical_count: number;
      submission_ready_claimed: boolean;
      final_eligibility_claimed: boolean;
      proposal_drafting_claimed: boolean;
      live_ingest_claimed: boolean;
      not_submission_ready_label: boolean;
      per_layer?: Record<string, string>;
      package_readiness: {
        eligibility_readiness: string;
        binder_readiness: string;
        checklist_readiness: string;
        intake_readiness: string;
        approval_readiness: string;
        narrative_scaffold_readiness: string;
        budget_match_readiness: string;
        overall_readiness_status: string;
      };
      operator_review_queue: {
        items: Array<{
          review_item_id: string;
          review_type: string;
          priority: string;
          issue_label: string;
          issue_summary: string;
          recommended_next_step?: string;
          unsupported_claim_guard?: boolean;
        }>;
      };
    }>;
  };
  organization_evidence_memory?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    profile_count: number;
    federal_count: number;
    state_only_count: number;
    customer_data_persistence_claimed: boolean;
    final_eligibility_claimed: boolean;
    live_ingest_claimed: boolean;
    fabricated_org_facts: boolean;
    federal_state_recognition_conflated: boolean;
    binary_upload_persistence_supported: boolean;
    buyer_summary: string[];
    cards: Array<{
      organization_evidence_profile_id: string;
      organization_profile_id: string;
      organization_name: string;
      recognition_status: string;
      recognition_tier: string;
      recognition_source?: string | null;
      uei_status: string;
      sam_status: string;
      service_geography?: string | null;
      evidence_status: string;
      missing_evidence: string[];
      missing_evidence_prompts: string[];
      approved_org_facts: Array<Record<string, unknown>>;
      prohibited_org_claims: string[];
      candidate_facts_needing_review?: Array<Record<string, unknown>>;
      standard_attachments: Array<Record<string, unknown>>;
      governance_documents: Array<Record<string, unknown>>;
      tribal_resolution_requirements: Array<Record<string, unknown>>;
      prior_awards: Array<Record<string, unknown>>;
      fiscal_sponsor_relationships: Array<Record<string, unknown>>;
      how_memory_helps_readiness: string[];
      human_review_required: boolean;
      customer_data_persistence_claimed: boolean;
      final_eligibility_claimed: boolean;
    }>;
    eligibility_integrations?: Array<Record<string, unknown>>;
  };
  nofo_extraction_pilot?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    pilot_opportunity_id: string;
    extraction_status: string;
    extraction_scope: string;
    extraction_mode: string;
    data_mode: string;
    source_document_label: string;
    document_url_or_fixture_reference: string;
    named_pdf_attachment_referenced?: string | null;
    section_extracted_count?: number;
    section_missing_count?: number;
    sections: Array<Record<string, unknown>>;
    requirements_map: Array<Record<string, unknown>>;
    buyer_summary: string[];
    honesty_notes: string[];
    full_pdf_extraction_claimed: boolean;
    broad_pdf_support_claimed: boolean;
    proposal_drafting_claimed: boolean;
    final_eligibility_claimed: boolean;
    live_ingest_claimed: boolean;
    pdf_bytes_parsed: boolean;
    human_review_required: boolean;
    integration?: Record<string, unknown>;
  };
  source_freshness_pilot?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    source_count: number;
    data_mode: string;
    external_live_check_not_run: boolean;
    live_ingest_claimed: boolean;
    continuous_monitoring_claimed: boolean;
    production_activation_claimed: boolean;
    buyer_summary: string[];
    records: Array<{
      source_id: string;
      source_name: string;
      source_layer: string;
      source_type: string;
      data_mode: string;
      freshness_status: string;
      source_health: string;
      last_checked_at?: string | null;
      retrieval_status: string;
      change_status: string;
      known_deadline_risk: string;
      known_expiration_risk: string;
      operator_next_check: string;
      live_ingest_claimed: boolean;
      continuous_monitoring_claimed: boolean;
      production_activation_claimed: boolean;
      notes?: string[];
    }>;
    duplicate_warnings?: string[];
    what_must_be_verified_before_customer_reliance?: string[];
    readiness_integration?: Record<string, unknown>;
  };
  draft_workspace?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    ai_drafting_enabled: boolean;
    generated_prose_present: boolean;
    customer_prose_persistence_claimed: boolean;
    final_application_claimed: boolean;
    submission_ready_claimed: boolean;
    proposal_drafting_claimed: boolean;
    live_ingest_claimed: boolean;
    human_review_required: boolean;
    workspaces: Array<{
      draft_workspace_id: string;
      application_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      draft_mode: string;
      draft_status: string;
      section_count: number;
      ai_drafting_enabled: boolean;
      generated_prose_present: boolean;
      customer_prose_persistence_claimed: boolean;
      submission_ready_claimed: boolean;
      human_review_required: boolean;
      sections: Array<{
        draft_section_id: string;
        section_id: string;
        section_label: string;
        text_source: string;
        imported_text?: string | null;
        generated_text: null;
        evidence_references: string[];
        missing_evidence: string[];
        unsupported_claim_flags: Array<Record<string, unknown>>;
        missing_citation_flags: Array<Record<string, unknown>>;
        review_status: string;
        reviewer_notes: string[];
        human_review_required: boolean;
        final_text_claimed: boolean;
      }>;
    }>;
  };
  controlled_drafting?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    complete_proposal_claimed: boolean;
    submission_ready_claimed: boolean;
    final_text_claimed: boolean;
    proposal_drafting_claimed: boolean;
    live_ingest_claimed: boolean;
    human_review_required: boolean;
    workspaces: Array<{
      opportunity_id: string;
      organization_profile_id: string;
      draft_workspace_id: string;
      draft_count: number;
      generated_from_evidence_count: number;
      placeholder_or_blocked_count: number;
      complete_proposal_claimed: boolean;
      submission_ready_claimed: boolean;
      final_text_claimed: boolean;
      human_review_required: boolean;
      drafts: Array<{
        section_id: string;
        drafting_mode: string;
        generation_status: string;
        generated_text?: string | null;
        placeholders: string[];
        question_prompts: string[];
        evidence_inputs: Array<Record<string, unknown>>;
        citation_requirements: string[];
        generated_draft_warning?: string;
        human_review_required: boolean;
        final_text_claimed: boolean;
        submission_ready_claimed: boolean;
        complete_proposal_claimed: boolean;
      }>;
    }>;
  };
  ai_governance?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    qa_passed: boolean;
    export_allowed: boolean;
    submission_allowed: boolean;
    submission_ready_claimed: boolean;
    final_application_claimed: boolean;
    final_eligibility_claimed: boolean;
    live_ingest_claimed: boolean;
    human_review_required: boolean;
    governance_complete_claimed: boolean;
    workspaces: Array<{
      draft_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      overall_qa_status: string;
      qa_passed: boolean;
      blocker_count: number;
      check_count: number;
      hard_blockers: Array<Record<string, unknown>>;
      per_section_qa: Array<Record<string, unknown>>;
      reviewer_actions: string[];
      customer_actions: string[];
      operator_actions: string[];
      export_allowed: boolean;
      submission_allowed: boolean;
      human_review_required: boolean;
      what_must_be_fixed_before_export_review: string[];
    }>;
  };
  feedback_loop?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    route: string;
    report_hook_count: number;
    report_hooks: Array<{
      surface_id: string;
      user_visible_label: string;
      route: string;
      page_id: string;
      report_hook_available: boolean;
      dialog_hook_supported: boolean;
    }>;
    sample_reports: Array<Record<string, unknown>>;
    buyer_summary: string[];
    slack_live_sent_claimed: boolean;
    persistence_claimed: boolean;
    live_ingest_claimed: boolean;
    collaboration: {
      collaboration_feature_enabled: boolean;
      collaboration_global_enabled: boolean;
      collaboration_cohort_enabled: boolean;
      organization_opt_in_required: boolean;
      partner_matching_live_claimed: boolean;
      cohort_rollout_claimed: boolean;
      global_rollout_claimed: boolean;
      buyer_summary: string[];
    };
  };
  package_export_preview?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    export_allowed: boolean;
    final_export_claimed: boolean;
    submission_ready_claimed: boolean;
    final_application_claimed: boolean;
    download_supported: boolean;
    human_review_required: boolean;
    live_ingest_claimed: boolean;
    workspaces: Array<{
      package_export_preview_id: string;
      application_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      export_mode: string;
      export_status: string;
      included_sections: Array<Record<string, unknown>>;
      excluded_sections: Array<Record<string, unknown>>;
      missing_items: string[];
      blocked_items: string[];
      review_required_items: string[];
      evidence_map: Array<Record<string, unknown>>;
      human_review_required: boolean;
      export_allowed: boolean;
      final_export_claimed: boolean;
      submission_ready_claimed: boolean;
      download_supported: boolean;
    }>;
  };
  forms_attachments_map?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    binary_upload_supported: boolean;
    attachment_persistence_claimed: boolean;
    form_completion_claimed: boolean;
    submission_ready_claimed: boolean;
    human_review_required: boolean;
    live_ingest_claimed: boolean;
    workspaces: Array<{
      forms_attachment_map_id: string;
      application_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      mapping_status: string;
      form_items: Array<Record<string, unknown>>;
      attachment_items: Array<Record<string, unknown>>;
      known_forms: Array<Record<string, unknown>>;
      likely_forms: Array<Record<string, unknown>>;
      unknown_forms: Array<Record<string, unknown>>;
      known_attachments: Array<Record<string, unknown>>;
      missing_attachments: Array<Record<string, unknown>>;
      human_review_required: boolean;
      binary_upload_supported: boolean;
      attachment_persistence_claimed: boolean;
      form_completion_claimed: boolean;
      submission_ready_claimed: boolean;
    }>;
  };
  multi_org_pilot?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    selected_organization_profile_id?: string | null;
    collaboration_enabled: boolean;
    customer_data_persistence_claimed: boolean;
    production_multi_tenant_claimed: boolean;
    live_customer_login_claimed: boolean;
    live_ingest_claimed: boolean;
    submission_ready_claimed: boolean;
    final_export_claimed: boolean;
    human_review_required: boolean;
    cohort: {
      pilot_cohort_id: string;
      cohort_label: string;
      cohort_data_mode: string;
      organization_count: number;
      organization_profile_ids: string[];
      collaboration_enabled: boolean;
      production_multi_tenant_claimed: boolean;
      live_customer_login_claimed: boolean;
    };
    organizations: Array<{
      organization_profile_id: string;
      organization_name?: string | null;
      recognition_status?: string | null;
      overall_readiness_status: string;
      opportunity_count: number;
      blockers: string[];
      qa_blocker_count: number;
      customer_actions: string[];
      operator_actions: string[];
      feedback_context_id: string;
      evidence_memory: Record<string, unknown>;
      next_safest_action: string;
      export_allowed: boolean;
      submission_ready_claimed: boolean;
      final_export_claimed: boolean;
    }>;
    operator_rollup: {
      org_count: number;
      package_count: number;
      opportunities_under_review: number;
      readiness_by_org: Record<string, string | undefined>;
      blockers_by_org: Record<string, string[]>;
      cohort_next_safest_action: string;
      production_multi_tenant_claimed: boolean;
      live_customer_login_claimed: boolean;
      collaboration_enabled: boolean;
    };
  };
  collaboration_dark_launch?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    collaboration_feature_enabled: boolean;
    collaboration_global_enabled: boolean;
    collaboration_cohort_enabled: boolean;
    organization_opt_in_required: boolean;
    data_sharing_allowed: boolean;
    partner_matching_live_claimed: boolean;
    partner_recommendations_claimed: boolean;
    fit_score_claimed: boolean;
    cohort_rollout_claimed: boolean;
    global_rollout_claimed: boolean;
    introduction_claimed: boolean;
    operator_review_required: boolean;
    consent: Record<string, unknown>;
    fit_model: {
      feature_enabled: boolean;
      fit_score_claimed: boolean;
      partner_recommendation_claimed: boolean;
      partner_names_surfaced: boolean;
      not_live_reason: string;
      dimensions: Array<Record<string, unknown>>;
    };
    rollout_controls: {
      rollout_stage: string;
      feature_exposure_status: string;
      collaboration_feature_enabled: boolean;
      collaboration_global_enabled: boolean;
      collaboration_cohort_enabled: boolean;
    };
  };
  evidence_intake?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    storage_modes_in_use: string[];
    storage_adapter: string;
    upload_ui_supported: boolean;
    upload_persistence_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    production_storage_claimed: boolean;
    package_unlock_claimed: boolean;
    submission_ready_claimed: boolean;
    final_export_claimed: boolean;
    migration_required: boolean;
    storage_proposal_path: string;
    human_review_required: boolean;
    workspaces: Array<{
      organization_profile_id: string;
      record_count: number;
      records: Array<Record<string, unknown>>;
      unlock_evaluation: Record<string, unknown>;
      customer_actions: string[];
      operator_actions: string[];
      upload_persistence_claimed: boolean;
      package_unlock_claimed: boolean;
      human_review_required: boolean;
      storage_adapter: string;
      upload_ui_supported: boolean;
    }>;
  };
  operator_readiness?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    monday_demo_status?: string;
    internal_pilot_status?: string;
    controlled_customer_pilot_status?: string;
    production_rollout_status?: string;
    upload_rollout_status?: string;
    collaboration_rollout_status?: string;
    live_source_rollout_status?: string;
    go_no_go_matrix: Array<Record<string, unknown>>;
    blockers: string[];
    operator_next_actions: string[];
    required_commands: string[];
    smoke_commands: string[];
    production_ready_claimed: boolean;
    pen_test_passed_claimed: boolean;
    upload_persistence_claimed: boolean;
    submission_ready_claimed: boolean;
    final_export_claimed: boolean;
    collaboration_matching_claimed: boolean;
    live_customer_login_claimed: boolean;
    contract: {
      current_head: string;
      route: string;
      production_readiness_status: string;
      upload_persistence_status: string;
      collaboration_status: string;
      multi_org_status: string;
      test_posture_reference: string;
      security_posture_reference: string;
      pen_test_readiness_reference: string;
    };
  };
  persistence_approval_gate?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    owner_approval_status: string;
    approval_scope?: string;
    approved_environment?: string;
    migration_required: boolean;
    migration_applied: boolean;
    migration_environment?: string | null;
    validated_persistent_adapter_claimed: boolean;
    validated_persistent_scope?: string | null;
    upload_persistence_claimed: boolean;
    upload_persistence_scope?: string | null;
    customer_data_persistence_claimed: boolean;
    production_storage_claimed: boolean;
    login_live_claimed?: boolean;
    controlled_customer_pilot_status?: string;
    dry_run_status: string;
    next_safe_action: string;
    approval_request_text?: string;
    storage_adapters: string[];
    what_remains_blocked_for_production?: string[];
    gate: Record<string, unknown>;
    dry_run: Record<string, unknown>;
  };
  customer_pilot_auth?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    boundary_count: number;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    rbac_enforced_claimed: boolean;
    production_multi_tenant_claimed: boolean;
    customer_data_isolation_claimed: boolean;
    controlled_customer_pilot_status: string;
    blockers: string[];
    next_safe_actions: string[];
    readiness_checklist: Record<string, unknown>;
    boundaries: Array<Record<string, unknown>>;
  };
  gate10_closeout?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    monday_demo_status: string;
    internal_pilot_status: string;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    production_multi_tenant_claimed: boolean;
    pen_test_passed_claimed: boolean;
    sca_passed_claimed: boolean;
    final_allowed_claims: string[];
    final_forbidden_claims: string[];
    final_fallback_path: string;
  };
  national_coverage?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    top_15_count: number;
    top_15_states: Array<{ state_code: string; state_name: string }>;
    active_customer_lane: string;
    live_coverage_claimed: boolean;
    ranking_confidence_summary: string;
    what_is_live: string[];
    what_is_modeled_only: string[];
    what_needs_research: string[];
    federally_recognized_tribe_source: string;
  };
  applicant_authority?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    submission_authority_claimed: boolean;
    federal_authority_claimed: boolean;
    state_authority_claimed: boolean;
    human_review_required: boolean;
    verification_confidence: string;
    missing_evidence: string[];
    allowed_actions: string[];
    blocked_actions: string[];
    selected_person: Record<string, unknown>;
    federal_authority: Record<string, unknown>;
    state_authority: Record<string, unknown>;
  };
  evidence_lifecycle?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    audit_event_count: number;
    submission_unlock_status: boolean;
    production_policy_validated: boolean;
    legal_compliance_claimed: boolean;
    package_unlock_behavior: string;
    export_unlock_behavior: string;
  };
  top15_source_validation?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    packet_count: number;
    states_packeted: string[];
    active_customer_lane: string;
    all_top15_live_claimed: boolean;
    non_sc_live_coverage_claimed: boolean;
    sc_packet: Record<string, unknown>;
    resolutions: Array<Record<string, unknown>>;
  };
  production_enforcement?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    local_dev_persistence_validated: boolean;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    production_multi_tenant_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    tenant_isolation_status: string;
    blockers: string[];
    next_safe_actions: string[];
  };
  gate13_pentest_pilot?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    pen_test_passed_claimed: boolean;
    sca_passed_claimed: boolean;
    sca_run: boolean;
    login_live_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    blockers: string[];
    allowed_claims: string[];
    forbidden_claims: string[];
  };
  live_authority_spike?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    states_covered: string[];
    sam_uei_live_checked: boolean;
    sam_uei_verified_claimed: boolean;
    ebiz_poc_live_checked: boolean;
    ebiz_poc_verified_claimed: boolean;
    aor_live_checked: boolean;
    aor_verified_claimed: boolean;
    state_authority_live_checked: boolean;
    state_authority_verified_claimed: boolean;
    submit_authority: boolean;
    draft_authority: boolean;
    manage_workspace_authority: boolean;
    login_live_claimed: boolean;
    human_review_required: boolean;
  };
  sca_security_loop?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    sca_run: boolean;
    sca_passed_claimed: boolean;
    npm_audit_clean?: boolean;
    pip_audit_clean?: boolean;
    high_critical_findings: string[];
    blocked_checks: string[];
    unresolved_findings: string[];
    remediated_items: string[];
    pen_test_passed_claimed: boolean;
    uv_lock_touched: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    login_live_claimed: boolean;
    human_review_required: boolean;
  };
  rbac_enforcement?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    auth_mode: string;
    login_live_claimed: boolean;
    external_auth_configured: boolean;
    production_auth_claimed: boolean;
    rbac_enforced_claimed: boolean;
    production_multi_tenant_claimed: boolean;
    rbac_policy_status: string;
    enforcement_status: string;
    denied_actions_default: string[];
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
    fake_login_ui_exposed: boolean;
  };
  audit_operator_storage?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    operator_queue_count?: number;
    owner_approval_needed: boolean;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    pilot_blocker_matrix: string[];
    production_blocker_matrix: string[];
    next_safe_actions: string[];
    login_live_claimed: boolean;
    audit_compliance_complete_claimed: boolean;
  };
  external_pilot_auth?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    recommended_auth_path: string;
    invite_status: string;
    external_auth_configured: boolean;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    pilot_go_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
    fake_login_ui_exposed: boolean;
  };
  storage_sca_pentest?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    production_storage_approved: boolean;
    production_storage_validated: boolean;
    customer_data_persistence_claimed: boolean;
    python_sca_run: boolean;
    python_sca_passed: boolean;
    full_sca_passed_claimed: boolean;
    uv_lock_touched: boolean;
    pen_test_passed_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
  };
  oidc_live_path?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    provider_configured: boolean;
    provider_validated: boolean;
    login_live_claimed: boolean;
    owner_setup_checklist: string;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
    fake_login_ui_exposed: boolean;
  };
  storage_pentest_support?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    owner_approval_status: string;
    dry_run_status: string;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    pen_test_passed_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
    login_live_claimed: boolean;
  };
  auth0_validation?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    provider_configured: boolean;
    secret_present: boolean;
    provider_validated: boolean;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    controlled_pilot_auth_ready: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
    fake_login_ui_exposed: boolean;
  };
  storage_feature_flags?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    local_dev_storage_enabled: boolean;
    production_storage_enabled: boolean;
    owner_approval_present: boolean;
    production_adapter_status?: string;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    controlled_pilot_storage_ready: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
  };
  auth0_live_validation?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    config_present: boolean;
    secret_present: boolean;
    validation_possible: boolean;
    dry_run_status?: string;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    controlled_pilot_auth_ready: boolean;
    operator_approval_needed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
    secret_value_printed: boolean;
  };
  storage_pilot_gate?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    owner_approval_present: boolean;
    approval_scope?: string;
    dry_run_allowed: boolean;
    real_provisioning_allowed: boolean;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
  };
  auth0_mode_b?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    mode_detected: string;
    auth0_config_present: boolean;
    secret_present: boolean;
    live_validation_possible: boolean;
    live_validation_attempted: boolean;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    controlled_pilot_auth_ready: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
    secret_value_printed: boolean;
  };
  gate20_closeout?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    mode?: string;
    storage_mode_b_possible: boolean;
    owner_approval_present: boolean;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    pen_test_evidence_captured: boolean;
    pen_test_passed_claim: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    estimated_maturity_pct?: number;
    next_safe_actions: string[];
  };
  auth0_mode_b_live_unlock?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    mode_detected: string;
    owner_config_present: boolean;
    secret_present_flag: boolean;
    live_validation_attempted: boolean;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    controlled_pilot_auth_ready: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
    secret_value_printed: boolean;
  };
  gate21_storage_pilot?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    owner_storage_approval_present: boolean;
    approval_valid: boolean;
    provisioning_validation_attempted: boolean;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    pen_test_evidence_captured: boolean;
    pen_test_passed: boolean;
    final_controlled_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
  };
  production_metadata?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    metadata_adapter_interface: boolean;
    local_dev_metadata_behavior: string;
    production_metadata_config_present: boolean;
    owner_approval_present: boolean;
    production_metadata_writes_allowed: boolean;
    tenant_org_scoping: boolean;
    audit_linkage: boolean;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
  };
  object_storage_signed_url?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    object_storage_adapter: boolean;
    production_object_config_present: boolean;
    signed_upload_url_path?: string;
    signed_download_url_path?: string;
    malware_scan_hook?: string;
    production_writes_allowed: boolean;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    fake_upload_ui_exposed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
  };
  customer_data_policy?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    customer_data_policy_contract: boolean;
    ai_training_consent_default: boolean;
    ai_training_consent: boolean;
    organization_policy_status: string;
    customer_persistence_resolver: boolean;
    customer_data_persistence_claimed: boolean;
    customer_data_policy_production_claimed: boolean;
    legal_compliance_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
  };
  retention_delete_export?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    retention_policy_contract: boolean;
    deletion_request_contract: boolean;
    export_request_contract: boolean;
    audit_linkage: boolean;
    production_delete_status?: string;
    export_status?: string;
    final_export_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    legal_compliance_claimed: boolean;
    fake_production_export_ui: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
  };
  auth0_login_rbac?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    auth_validation_run_model: boolean;
    mode: string;
    provider_config_present: boolean;
    secret_present: boolean;
    live_validation_attempted: boolean;
    invite_binding_passed: boolean;
    org_binding_passed: boolean;
    role_mapping_passed: boolean;
    rbac_handoff_passed: boolean;
    tenant_boundary_passed: boolean;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    controlled_pilot_auth_ready: boolean;
    fake_login_ui: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  session_tenant_enforcement?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    session_context_contract: boolean;
    session_status?: string;
    operator_only_route_protection: boolean;
    customer_route_constraints: boolean;
    cross_org_denial_behavior: string;
    denial_audit_events: boolean;
    production_multi_tenant_claimed: boolean;
    external_users_can_access_claimed: boolean;
    login_live_claimed: boolean;
    fake_customer_access_ui: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_safe_actions: string[];
  };
  storage_approval_metadata?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    storage_approval_ingest_service: boolean;
    mode: string;
    approval_token_present: boolean;
    approval_valid: boolean;
    approval_scope: string;
    metadata_config_present: boolean;
    metadata_writes_allowed: boolean;
    production_storage_claimed: boolean;
    customer_persistence_claimed: boolean;
    prompt_alone_is_not_approval: boolean;
    fake_upload_ui: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  object_storage_unlock?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    object_storage_approval_resolver: boolean;
    object_config_present: boolean;
    signed_upload_status?: string;
    signed_download_status?: string;
    path_traversal_protection: boolean;
    production_object_writes_allowed: boolean;
    signed_urls_live: boolean;
    production_storage_claimed: boolean;
    customer_persistence_claimed: boolean;
    controlled_pilot_storage_ready: boolean;
    fake_upload_ui: boolean;
    fake_signed_url_ui: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  security_attestation?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    security_attestation_contract: boolean;
    evidence_report_present: boolean;
    evidence_status: string;
    critical_high_open: number;
    remediation_status: string;
    retest_status: string;
    pen_test_passed: boolean;
    pass_claimed: boolean;
    pilot_impact: string;
    production_impact: string;
    fake_secure_badge: boolean;
    fake_pen_test_passed_badge: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  controlled_pilot_master?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    master_resolver: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    allowed_claims?: string[];
    forbidden_claims?: string[];
    missing_gates?: string[];
    fake_pilot_ready_banner: boolean;
    fake_secure_badge: boolean;
    login_live_claimed: boolean;
    production_storage_claimed: boolean;
    customer_persistence_claimed: boolean;
    pen_test_passed_claimed: boolean;
    next_owner_actions?: string[];
    next_safe_actions: string[];
  };
  owner_unlock_packet?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    owner_unlock_packet_contract: boolean;
    mode: string;
    mode_b_ready: boolean;
    mode_b_executed: boolean;
    auth0_complete: boolean;
    storage_complete: boolean;
    security_ready_for_ingest: boolean;
    missing_owner_inputs?: string[];
    no_secret_validation: boolean;
    login_live_claimed: boolean;
    production_storage_claimed: boolean;
    pen_test_passed_claimed: boolean;
    fake_mode_b: boolean;
    prompt_alone_is_not_approval: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  cutover_claim_freeze?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    production_cutover_checklist: boolean;
    claim_freeze_contract: boolean;
    allowed_claims?: string[];
    conditional_claims?: string[];
    forbidden_claims?: string[];
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    login_live_claimed: boolean;
    production_storage_claimed: boolean;
    fake_production_ready: boolean;
    fake_pilot_ready: boolean;
    fake_secure_badge: boolean;
    next_safe_actions: string[];
  };
  mode_b_rehearsal?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    rehearsal_contract: boolean;
    mode: string;
    real_owner_inputs_present: boolean;
    synthetic_fixture_used: boolean;
    auth0_rehearsed: boolean;
    storage_rehearsed: boolean;
    pen_test_rehearsed: boolean;
    claim_freeze_verified: boolean;
    mode_b_executed_claimed: boolean;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    production_storage_claimed: boolean;
    customer_persistence_claimed: boolean;
    pen_test_passed_claimed: boolean;
    controlled_customer_pilot_go_claimed: boolean;
    missing_real_inputs?: string[];
    no_secret_validation: boolean;
    fake_mode_b: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  dry_run_cutover?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    dry_run_cutover_contract: boolean;
    first_hard_blocker?: string | null;
    downstream_step_handling: string;
    skipped_after_blocker_count?: number;
    sca_evidence_check?: string;
    final_freeze_verified: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    production_cutover_executed: boolean;
    login_live_claimed: boolean;
    production_storage_claimed: boolean;
    pen_test_passed_claimed: boolean;
    fake_cutover_complete: boolean;
    fake_pilot_ready: boolean;
    owner_next_action?: string;
    next_safe_actions: string[];
  };
  auth0_real_input?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    real_input_detector: boolean;
    mode: string;
    synthetic_rehearsal_artifacts_ignored: boolean;
    real_owner_auth0_inputs_present: boolean;
    secret_present_redacted: boolean;
    live_validation_enabled: boolean;
    live_validation_attempted: boolean;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    controlled_pilot_auth_ready: boolean;
    mode_b_executed_claimed: boolean;
    missing_gates?: string[];
    no_secret_validation: boolean;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  storage_security_real_input?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    real_storage_input_detector: boolean;
    real_pen_test_evidence_detector: boolean;
    synthetic_rehearsal_artifacts_ignored: boolean;
    approval_token_present: boolean;
    approval_token_valid: boolean;
    production_storage_validation_attempted: boolean;
    production_storage_claimed: boolean;
    customer_persistence_claimed: boolean;
    real_pen_test_evidence_present: boolean;
    pen_test_pass_claimed: boolean;
    claim_freeze_verified: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    missing_gates?: string[];
    fake_pilot_ready: boolean;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  final_closeout?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    final_pilot_resolver: boolean;
    final_production_rollout_resolver: boolean;
    final_claim_freeze: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    allowed_claims?: string[];
    forbidden_claims?: string[];
    login_live_claimed: boolean;
    production_storage_claimed: boolean;
    pen_test_passed_claimed: boolean;
    mode_b_executed_claimed: boolean;
    fake_pilot_ready: boolean;
    fake_production_ready: boolean;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  buyer_trust?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    buyer_trust_contract: boolean;
    views?: Array<{
      view_id: string;
      title: string;
      answers: Record<string, string | undefined>;
      allowed_claims?: string[];
      forbidden_claims?: string[];
      blocker_reason?: string;
      evidence_refs?: string[];
      owner_next_action?: string;
      fake_green_badge: boolean;
    }>;
    safe_verbs?: string[];
    talk_track?: string[];
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    login_live_claimed: boolean;
    production_storage_claimed: boolean;
    pen_test_passed_claimed: boolean;
    fake_green_badge: boolean;
    fake_pilot_ready_banner: boolean;
    fake_production_ready: boolean;
    blockers_exposed: boolean;
    owner_next_action_exposed: boolean;
    claim_freeze_visible: boolean;
    demo_safe: boolean;
    next_owner_action?: string;
    allowed_claims?: string[];
    forbidden_claims?: string[];
    next_safe_actions: string[];
  };
  live_authority_execution?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    authority_execution_contract: boolean;
    live_check_attempted: boolean;
    sam_uei_status?: string;
    grants_gov_aor_ebiz_status?: string;
    tribal_delegation_resolution_status?: string;
    state_portal_authority_status?: string;
    manual_evidence_fallback: boolean;
    human_review_required: boolean;
    can_view: boolean;
    can_draft: boolean;
    can_submit: boolean;
    final_authority_claim: boolean;
    final_eligibility_claim: boolean;
    submission_ready_claim: boolean;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  live_source_coverage?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    source_coverage_execution_contract: boolean;
    source_packets_mapped?: number;
    read_only_checks_attempted?: boolean;
    top15_states?: string[];
    sc_status?: string;
    non_sc_status?: string;
    freshness_resolver: boolean;
    confidence_resolver: boolean;
    duplicate_detection: boolean;
    live_coverage_claimed: boolean;
    top15_live_claimed: boolean;
    broad_coverage_claimed: boolean;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  pilot_org_onboarding?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    pilot_org_onboarding_contract: boolean;
    invite_send_gate: boolean;
    invite_sent_claimed: boolean;
    customer_role_model?: string;
    allowed_route_set?: string[];
    blocked_route_set?: string[];
    operator_approval_gate: boolean;
    customer_access_claim: boolean;
    pilot_org_status?: string;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  support_triage?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    feedback_intake_contract: boolean;
    issue_triage_contract: boolean;
    owner_assignment: boolean;
    support_ready: boolean;
    slack_sent_claimed: boolean;
    incident_audit_events: boolean;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  source_freshness?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    source_freshness_contract: boolean;
    read_only_checks_attempted: boolean;
    live_source_claim: boolean;
    top15_live_claimed: boolean;
    broad_coverage_claimed: boolean;
    duplicate_detector: boolean;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  observability?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    observability_contract: boolean;
    health_checks: boolean;
    alert_readiness?: string;
    alert_sent_claimed: boolean;
    pilot_ops_readiness: boolean;
    production_monitoring_claimed: boolean;
    controlled_pilot_status: string;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  backup_restore?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    rollback_contract: boolean;
    backup_contract: boolean;
    restore_proof_contract: boolean;
    non_prod_backup_manifest: boolean;
    non_prod_restore_rehearsal: boolean;
    production_backup_claimed: boolean;
    production_restore_claimed: boolean;
    customer_persistence_claimed: boolean;
    production_rollback_claimed: boolean;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  launch_packet?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    launch_packet_contract: boolean;
    launch_status?: string;
    non_owner_blockers?: string[];
    owner_gated_blockers?: string[];
    external_vendor_blockers?: string[];
    next_action_sequence?: string[];
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    allowed_claims?: string[];
    forbidden_claims?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  source_probes?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    source_probe_contract: boolean;
    read_only_probes_attempted?: boolean;
    sources_probed?: number;
    live_source_claim: boolean;
    top15_live_claimed: boolean;
    broad_coverage_claimed: boolean;
    evidence_refs?: Array<string | null>;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  healthchecks?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    healthcheck_registry: boolean;
    alert_readiness?: string;
    alert_sent_claimed: boolean;
    pilot_ops_readiness: boolean;
    production_monitoring_claimed: boolean;
    error_budget?: string;
    controlled_pilot_status: string;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  restore_rehearsal?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    restore_rehearsal_contract: boolean;
    backup_manifest_evidence?: boolean;
    restore_attempted?: boolean;
    restore_completed?: boolean;
    restore_evidence_ref?: string | null;
    production_backup_claimed: boolean;
    production_restore_claimed: boolean;
    customer_persistence_claimed: boolean;
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  operator_runbooks?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    runbook_index: boolean;
    owner_gated_blockers?: string[];
    non_owner_items?: string[];
    next_action_sequence?: string[];
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    allowed_claims?: string[];
    forbidden_claims?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  owner_wait?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    wait_state_contract: boolean;
    no_progress_without_input: boolean;
    live_claims_unlocked: boolean;
    owner_blockers?: string[];
    external_vendor_blockers?: string[];
    policy_decision_blockers?: string[];
    missing_gates?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  talk_track?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    buyer_talk_track_contract: boolean;
    cta_safe: boolean;
    fake_claim_language_blocked: boolean;
    owner_action_exposed?: string;
    demo_narrative?: string;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  operator_drill?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    drill_contract: boolean;
    drills_passed?: string[];
    pilot_go_claimed: boolean;
    production_rollout_claimed: boolean;
    alert_sent_claimed: boolean;
    production_restore_claimed: boolean;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  pre_owner_closeout?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    closeout_packet_contract: boolean;
    owner_input_package_checklist?: string[];
    external_vendor_package_checklist?: string[];
    post_owner_rerun_sequence?: string[];
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    allowed_claims?: string[];
    forbidden_claims?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  auth0_ingest?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    real_artifacts_present: boolean;
    login_live_claim: boolean;
    production_auth_claim: boolean;
    live_validation_attempted: boolean;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  storage_ingest?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    approval_artifact_present: boolean;
    production_storage_claim: boolean;
    customer_persistence_claim: boolean;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  pentest_ingest?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    report_reference_present: boolean;
    pen_test_pass_claim: boolean;
    controlled_pilot_security_ready: boolean;
    production_rollout_security_ready: boolean;
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  /**
   * Gate 83 — applicant-class fit / negative intelligence.
   *
   * Produced by running the real Gate 82 ingestion pipeline over the committed
   * synthetic notice fixture, so `evidence_quote` is the sentence the parser
   * cited rather than demo copy. Synthetic throughout; claims no live coverage.
   */
  negative_intelligence?: {
    schema_version: string;
    surface_version: string;
    title: string;
    headline: string;
    why_it_matters: string;
    copy_concepts: string[];
    rows: Array<{
      demo_id: string;
      source_label: string;
      opportunity_title: string;
      funding_lane: string;
      applicant_class: string;
      applicant_class_label: string;
      relevance_status: string;
      eligibility_status: string;
      exclusion_status: string;
      exclusion_status_label: string;
      exclusion_reason: string;
      evidence_quote: string;
      evidence_span: number[] | null;
      evidence_reference?: string | null;
      has_citation: boolean;
      artifact_hash?: string | null;
      artifact_type?: string | null;
      text_extraction_method?: string | null;
      notice_status?: string | null;
      deadline_status: string;
      remains_visible: boolean;
      human_review_required: boolean;
      not_eligible_asserted: boolean;
    }>;
    excluded_class_count: number;
    eligible_class_count: number;
    applicant_class_changes_the_answer: boolean;
    artifact_hash?: string | null;
    artifact_type?: string | null;
    artifact_is_recorded_fixture: boolean;
    pipeline_status: string;
    adapter_confidence?: string | null;
    parser_confidence?: string | null;
    eligibility_confidence?: string | null;
    evidence_spans_relative_to?: string | null;
    synthetic_demo: boolean;
    demo_only: boolean;
    live_coverage_claimed: boolean;
    source_monitored: boolean;
    freshness_claimed: boolean;
    url_fetch_performed: boolean;
    excluded_hidden: boolean;
    final_eligibility_claimed: boolean;
    not_eligible_asserted: boolean;
  };
  pilot_resolver?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    controlled_customer_pilot_status: string;
    limited_external_validation_status?: string;
    production_rollout_status: string;
    allowed_claims?: string[];
    forbidden_claims?: string[];
    remaining_blockers?: string[];
    next_owner_action?: string;
    next_safe_actions: string[];
  };
  nofo_showcase?: {
    schema_version: string;
    title: string;
    pack_id: string;
    selected_count: number;
    sc_selected_count: number;
    federal_selected_count: number;
    live_ingest_claimed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    proposal_drafting_claimed: boolean;
    buyer_sections: string[];
    cards: Array<{
      opportunity_id: string;
      source_layer: string;
      source_name?: string | null;
      title?: string | null;
      data_mode?: string | null;
      live_ingest_claimed: boolean;
      human_review_required: boolean;
      field_status_counts: Record<string, number>;
      unresolved_fields: string[];
      what_nativeforge_found: Record<string, unknown>;
      what_this_means?: string | null;
      what_is_missing: Array<Record<string, unknown>>;
      what_needs_human_review: string[];
      what_to_do_next: string[];
      application_plan: {
        recommendation_label?: string;
        application_checklist?: Array<Record<string, unknown>>;
        narrative_section_scaffold?: Array<Record<string, unknown>>;
        forms_checklist?: Array<Record<string, unknown>>;
        attachment_checklist?: Array<Record<string, unknown>>;
        missing_information_questions?: Array<Record<string, unknown>>;
        completeness?: Record<string, unknown>;
        proposal_drafting_claimed: boolean;
        nofo_pdf_extraction_claimed: boolean;
      };
      evidence_provenance: Record<string, unknown>;
      limitations: string[];
    }>;
  };
};
