/** Types for SC Monday customer demo bridge payload (read-only). */

export type ScCustomerDemoRow = {
  profile_id: string;
  recognition_type: string;
  grant_id: string;
  opportunity_title: string;
  funding_geography: string;
  data_label: string;
  live_ingest_not_claimed: boolean;
  classification_label: string;
  match_readiness_label: string;
  discoverability: string;
  confidence: string;
  missing_data: string[];
  blockers: string[];
  operator_next_check: string[];
  provenance_evidence_notes: string[];
  human_review_required: boolean;
  final_eligibility_claim_allowed: boolean;
  confirm_active_round?: boolean;
  excluded_from_match_set?: boolean;
};

export type ScCustomerDemoPayload = {
  schema_version: string;
  title: string;
  demo_route_path: string;
  demo_dev_only: boolean;
  offline_only: boolean;
  read_only_advisory: boolean;
  live_ingestion: boolean;
  source_activation: boolean;
  external_urls_used: boolean;
  auth_required: boolean;
  final_eligibility_claim_allowed: boolean;
  pack_id: string;
  capture_date: string;
  content_digest: string;
  claim_matrix: Record<string, unknown>;
  profiles: {
    profile_count: number;
    federal_recognized_count: number;
    state_only_count: number;
    fixture_keys: string[];
  };
  opportunities: {
    total: number;
    south_carolina_count: number;
    federal_count: number;
    by_data_label: Record<string, number>;
    opportunity_ids: string[];
  };
  classify_match: Record<string, unknown>;
  combined_summary: {
    row_count: number;
    south_carolina_row_count: number;
    federal_row_count: number;
    human_review_required_count: number;
    confidence_distribution: Record<string, number>;
  };
  missing_data_summary: {
    rows_with_missing_data: number;
    hidden_missing_data: boolean;
  };
  provenance_evidence_summary: {
    notes_visible: boolean;
    pack_evidence_required: boolean;
  };
  what_nativeforge_did: string[];
  what_requires_attention: string[];
  why_this_matters?: string[];
  workload_reduction_statement?: string;
  next_actions: string[];
  rows: ScCustomerDemoRow[];
  row_sample_note?: string;
  ui_flags: {
    show_activation_controls: boolean;
    show_submit_controls: boolean;
    advisory_banner: string;
  };
  buyer_demo?: {
    schema_version: string;
    demo_route_path: string;
    opening_line: string;
    closing_line: string;
    required_story_labels: string[];
    allowed_claims: string[];
    forbidden_claims: string[];
    trust_cues_required?: string[];
    claim_matrix?: Record<string, string>;
    live_ingest_claimed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    proposal_drafting_claimed: boolean;
    final_eligibility_claim_allowed: boolean;
  };
  opportunity_engine?: {
    schema_version: string;
    campaign_block: number;
    block_name: string;
    live_ingest_claimed: boolean;
    source_activation_claimed: boolean;
    final_eligibility_claim_allowed: boolean;
    buyer_summary: string[];
    sc_state_adapter: Record<string, unknown>;
    combined_workflow: {
      counts: Record<string, number>;
      organization_geography_filters_federal: boolean;
      missing_data_summary: Record<string, unknown>;
      human_review: Record<string, unknown>;
      eligibility_readiness_handoff: Record<string, unknown>;
      eligibility_evidence_handoff?: {
        pair_count?: number;
        federal_pairs_visible?: boolean;
        final_eligibility_claimed?: boolean;
        scoring_math_changed?: boolean;
        human_review_required?: boolean;
        sample_pairs?: Array<Record<string, unknown>>;
      };
      provenance_summary: Record<string, unknown>;
      combined_ordering_sample: Array<Record<string, unknown>>;
      next_checks_sample: string[];
    };
  };
  pursuit_workspace?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    final_submission_allowed: boolean;
    submission_ready_claimed: boolean;
    proposal_drafting_claimed: boolean;
    live_ingest_claimed: boolean;
    scoring_math_changed: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      workspace: {
        pursuit_workspace_id: string;
        opportunity_id: string;
        organization_profile_id: string;
        opportunity_source_layer: string;
        readiness_status: string;
        pursuit_status: string;
        missing_information_summary: string[];
        human_review_required: boolean;
        operator_next_actions: string[];
        customer_next_actions: string[];
        why_worth_review?: string;
        final_submission_allowed: boolean;
        submission_ready_claimed: boolean;
        proposal_drafting_claimed: boolean;
        not_submission_ready_label?: boolean;
        what_nativeforge_prebuilt?: string[];
        what_customer_must_provide?: string[];
      };
      evidence_binder: {
        item_count: number;
        missing_or_needs_confirmation_ids: string[];
        human_review_required: boolean;
        proposal_drafting_claimed: boolean;
        submission_ready_claimed: boolean;
      };
      readiness: {
        readiness_status: string;
        not_submission_ready: boolean;
        operator_next_actions: string[];
        customer_next_actions: string[];
      };
      application_plan_summary?: Record<string, unknown>;
      nofo_intelligence_present?: boolean;
    }>;
  };
  application_plan_workspace?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    submission_allowed: boolean;
    submission_ready_claimed: boolean;
    proposal_drafting_claimed: boolean;
    application_complete_claimed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    live_ingest_claimed: boolean;
    scoring_math_changed: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      application_workspace: {
        application_workspace_id: string;
        pursuit_workspace_id: string;
        opportunity_id: string;
        organization_profile_id: string;
        section_count: number;
        item_count: number;
        checklist_sections: Array<{ section_id: string; title: string }>;
        checklist_items: Array<{
          item_id: string;
          section_id: string;
          label: string;
          item_status: string;
          what_nativeforge_knows?: string;
          what_is_missing?: string[];
          next_action?: string;
          required_human_review?: boolean;
          unsupported_claim_guard?: boolean;
        }>;
        submission_allowed: boolean;
        why_submission_not_allowed?: string;
      };
      questionnaire: {
        question_count: number;
        questions: Array<{
          question_id: string;
          group: string;
          prompt: string;
          answer: null;
        }>;
        customer_next_actions?: string[];
        operator_next_actions?: string[];
      };
      opportunity_id: string;
      organization_profile_id: string;
      opportunity_source_layer: string;
      incomplete_item_count: number;
      question_count: number;
      what_nativeforge_knows?: string[];
      what_customer_must_provide?: string[];
      what_requires_human_review?: string[];
      why_submission_not_allowed?: string;
      unsupported_claims?: string[];
      submission_allowed: boolean;
      proposal_drafting_claimed: boolean;
      application_complete_claimed: boolean;
    }>;
  };
  intake_approval_workspace?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    binary_upload_persistence_supported: boolean;
    binary_upload_persistence_claimed: boolean;
    approval_persistence_supported: boolean;
    approval_persistence_claimed: boolean;
    submission_allowed: boolean;
    submission_ready_claimed: boolean;
    proposal_drafting_claimed: boolean;
    package_readiness_unlocked: boolean;
    live_ingest_claimed: boolean;
    scoring_math_changed: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      application_workspace_id: string;
      pursuit_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      opportunity_source_layer: string;
      intake_item_count: number;
      approval_count: number;
      open_approval_count: number;
      customer_must_provide: string[];
      operator_must_verify: string[];
      required_reviewer_roles: string[];
      what_remains_blocked: string[];
      why_package_not_ready: string;
      binary_upload_persistence_supported: boolean;
      binary_upload_persistence_claimed: boolean;
      approval_persistence_supported: boolean;
      approval_persistence_claimed: boolean;
      submission_allowed: boolean;
      submission_ready_claimed: boolean;
      proposal_drafting_claimed: boolean;
      package_readiness_unlocked: boolean;
      intake_plan: {
        intake_items: Array<{
          intake_item_id: string;
          intake_type: string;
          item_label: string;
          current_status: string;
          accepted_evidence_types: string[];
          customer_action_required: boolean;
          operator_action_required: boolean;
          approval_status: string;
          why_it_matters?: string;
          what_remains_blocked?: string;
          source_checklist_section?: string;
        }>;
      };
      approval_workflow: {
        approvals: Array<{
          approval_id: string;
          approval_type: string;
          required_reviewer_role: string;
          approval_status: string;
          cannot_unlock_reason?: string;
        }>;
      };
    }>;
  };
  narrative_budget_scaffold?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    drafting_supported: boolean;
    generated_prose_produced: boolean;
    proposal_drafting_claimed: boolean;
    budget_claimed_complete: boolean;
    match_claimed_complete: boolean;
    live_ingest_claimed: boolean;
    scoring_math_changed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      application_workspace_id: string;
      pursuit_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      opportunity_source_layer: string;
      section_count: number;
      customer_questions: string[];
      operator_checks: string[];
      budget_customer_questions: string[];
      drafting_supported: boolean;
      generated_prose_produced: boolean;
      proposal_drafting_claimed: boolean;
      budget_claimed_complete: boolean;
      match_claimed_complete: boolean;
      why_drafting_not_supported: string;
      narrative_scaffold: {
        sections: Array<{
          section_id: string;
          section_label: string;
          section_type: string;
          section_required_status: string;
          known_evidence: string[];
          missing_evidence: string[];
          question_prompts: string[];
          drafting_supported: boolean;
          generated_prose: null;
          unsupported_claim_guard?: boolean;
        }>;
      };
      budget_match_evidence: {
        budget_required_status: string;
        match_required_status: string;
        cost_share_required_status: string;
        amount_requested_known: boolean;
        match_amount_known: boolean;
        missing_budget_facts: string[];
        customer_questions: string[];
        budget_claimed_complete: boolean;
        match_claimed_complete: boolean;
      };
    }>;
  };
  package_readiness_queue?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    showcase_opportunity_ids: string[];
    submission_ready_claimed: boolean;
    final_eligibility_claimed: boolean;
    proposal_drafting_claimed: boolean;
    live_ingest_claimed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    scoring_math_changed: boolean;
    not_submission_ready_label: boolean;
    buyer_summary: string[];
    workspaces: Array<{
      application_workspace_id: string;
      pursuit_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      opportunity_source_layer: string;
      overall_readiness_status: string;
      blocked_reasons: string[];
      missing_information_count: number;
      human_review_count: number;
      unsupported_capability_count: number;
      next_safest_action: string;
      customer_next_actions: string[];
      operator_next_actions: string[];
      review_item_count: number;
      critical_count: number;
      submission_ready_claimed: boolean;
      final_eligibility_claimed: boolean;
      proposal_drafting_claimed: boolean;
      live_ingest_claimed: boolean;
      not_submission_ready_label: boolean;
      per_layer?: Record<string, string>;
      package_readiness: {
        eligibility_readiness: string;
        binder_readiness: string;
        checklist_readiness: string;
        intake_readiness: string;
        approval_readiness: string;
        narrative_scaffold_readiness: string;
        budget_match_readiness: string;
        overall_readiness_status: string;
      };
      operator_review_queue: {
        items: Array<{
          review_item_id: string;
          review_type: string;
          priority: string;
          issue_label: string;
          issue_summary: string;
          recommended_next_step?: string;
          unsupported_claim_guard?: boolean;
        }>;
      };
    }>;
  };
  organization_evidence_memory?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    profile_count: number;
    federal_count: number;
    state_only_count: number;
    customer_data_persistence_claimed: boolean;
    final_eligibility_claimed: boolean;
    live_ingest_claimed: boolean;
    fabricated_org_facts: boolean;
    federal_state_recognition_conflated: boolean;
    binary_upload_persistence_supported: boolean;
    buyer_summary: string[];
    cards: Array<{
      organization_evidence_profile_id: string;
      organization_profile_id: string;
      organization_name: string;
      recognition_status: string;
      recognition_tier: string;
      recognition_source?: string | null;
      uei_status: string;
      sam_status: string;
      service_geography?: string | null;
      evidence_status: string;
      missing_evidence: string[];
      missing_evidence_prompts: string[];
      approved_org_facts: Array<Record<string, unknown>>;
      prohibited_org_claims: string[];
      candidate_facts_needing_review?: Array<Record<string, unknown>>;
      standard_attachments: Array<Record<string, unknown>>;
      governance_documents: Array<Record<string, unknown>>;
      tribal_resolution_requirements: Array<Record<string, unknown>>;
      prior_awards: Array<Record<string, unknown>>;
      fiscal_sponsor_relationships: Array<Record<string, unknown>>;
      how_memory_helps_readiness: string[];
      human_review_required: boolean;
      customer_data_persistence_claimed: boolean;
      final_eligibility_claimed: boolean;
    }>;
    eligibility_integrations?: Array<Record<string, unknown>>;
  };
  nofo_extraction_pilot?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    pilot_opportunity_id: string;
    extraction_status: string;
    extraction_scope: string;
    extraction_mode: string;
    data_mode: string;
    source_document_label: string;
    document_url_or_fixture_reference: string;
    named_pdf_attachment_referenced?: string | null;
    section_extracted_count?: number;
    section_missing_count?: number;
    sections: Array<Record<string, unknown>>;
    requirements_map: Array<Record<string, unknown>>;
    buyer_summary: string[];
    honesty_notes: string[];
    full_pdf_extraction_claimed: boolean;
    broad_pdf_support_claimed: boolean;
    proposal_drafting_claimed: boolean;
    final_eligibility_claimed: boolean;
    live_ingest_claimed: boolean;
    pdf_bytes_parsed: boolean;
    human_review_required: boolean;
    integration?: Record<string, unknown>;
  };
  source_freshness_pilot?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    source_count: number;
    data_mode: string;
    external_live_check_not_run: boolean;
    live_ingest_claimed: boolean;
    continuous_monitoring_claimed: boolean;
    production_activation_claimed: boolean;
    buyer_summary: string[];
    records: Array<{
      source_id: string;
      source_name: string;
      source_layer: string;
      source_type: string;
      data_mode: string;
      freshness_status: string;
      source_health: string;
      last_checked_at?: string | null;
      retrieval_status: string;
      change_status: string;
      known_deadline_risk: string;
      known_expiration_risk: string;
      operator_next_check: string;
      live_ingest_claimed: boolean;
      continuous_monitoring_claimed: boolean;
      production_activation_claimed: boolean;
      notes?: string[];
    }>;
    duplicate_warnings?: string[];
    what_must_be_verified_before_customer_reliance?: string[];
    readiness_integration?: Record<string, unknown>;
  };
  draft_workspace?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    ai_drafting_enabled: boolean;
    generated_prose_present: boolean;
    customer_prose_persistence_claimed: boolean;
    final_application_claimed: boolean;
    submission_ready_claimed: boolean;
    proposal_drafting_claimed: boolean;
    live_ingest_claimed: boolean;
    human_review_required: boolean;
    workspaces: Array<{
      draft_workspace_id: string;
      application_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      draft_mode: string;
      draft_status: string;
      section_count: number;
      ai_drafting_enabled: boolean;
      generated_prose_present: boolean;
      customer_prose_persistence_claimed: boolean;
      submission_ready_claimed: boolean;
      human_review_required: boolean;
      sections: Array<{
        draft_section_id: string;
        section_id: string;
        section_label: string;
        text_source: string;
        imported_text?: string | null;
        generated_text: null;
        evidence_references: string[];
        missing_evidence: string[];
        unsupported_claim_flags: Array<Record<string, unknown>>;
        missing_citation_flags: Array<Record<string, unknown>>;
        review_status: string;
        reviewer_notes: string[];
        human_review_required: boolean;
        final_text_claimed: boolean;
      }>;
    }>;
  };
  controlled_drafting?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    complete_proposal_claimed: boolean;
    submission_ready_claimed: boolean;
    final_text_claimed: boolean;
    proposal_drafting_claimed: boolean;
    live_ingest_claimed: boolean;
    human_review_required: boolean;
    workspaces: Array<{
      opportunity_id: string;
      organization_profile_id: string;
      draft_workspace_id: string;
      draft_count: number;
      generated_from_evidence_count: number;
      placeholder_or_blocked_count: number;
      complete_proposal_claimed: boolean;
      submission_ready_claimed: boolean;
      final_text_claimed: boolean;
      human_review_required: boolean;
      drafts: Array<{
        section_id: string;
        drafting_mode: string;
        generation_status: string;
        generated_text?: string | null;
        placeholders: string[];
        question_prompts: string[];
        evidence_inputs: Array<Record<string, unknown>>;
        citation_requirements: string[];
        generated_draft_warning?: string;
        human_review_required: boolean;
        final_text_claimed: boolean;
        submission_ready_claimed: boolean;
        complete_proposal_claimed: boolean;
      }>;
    }>;
  };
  ai_governance?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    qa_passed: boolean;
    export_allowed: boolean;
    submission_allowed: boolean;
    submission_ready_claimed: boolean;
    final_application_claimed: boolean;
    final_eligibility_claimed: boolean;
    live_ingest_claimed: boolean;
    human_review_required: boolean;
    governance_complete_claimed: boolean;
    workspaces: Array<{
      draft_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      overall_qa_status: string;
      qa_passed: boolean;
      blocker_count: number;
      check_count: number;
      hard_blockers: Array<Record<string, unknown>>;
      per_section_qa: Array<Record<string, unknown>>;
      reviewer_actions: string[];
      customer_actions: string[];
      operator_actions: string[];
      export_allowed: boolean;
      submission_allowed: boolean;
      human_review_required: boolean;
      what_must_be_fixed_before_export_review: string[];
    }>;
  };
  feedback_loop?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    route: string;
    report_hook_count: number;
    report_hooks: Array<{
      surface_id: string;
      user_visible_label: string;
      route: string;
      page_id: string;
      report_hook_available: boolean;
      dialog_hook_supported: boolean;
    }>;
    sample_reports: Array<Record<string, unknown>>;
    buyer_summary: string[];
    slack_live_sent_claimed: boolean;
    persistence_claimed: boolean;
    live_ingest_claimed: boolean;
    collaboration: {
      collaboration_feature_enabled: boolean;
      collaboration_global_enabled: boolean;
      collaboration_cohort_enabled: boolean;
      organization_opt_in_required: boolean;
      partner_matching_live_claimed: boolean;
      cohort_rollout_claimed: boolean;
      global_rollout_claimed: boolean;
      buyer_summary: string[];
    };
  };
  package_export_preview?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    export_allowed: boolean;
    final_export_claimed: boolean;
    submission_ready_claimed: boolean;
    final_application_claimed: boolean;
    download_supported: boolean;
    human_review_required: boolean;
    live_ingest_claimed: boolean;
    workspaces: Array<{
      package_export_preview_id: string;
      application_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      export_mode: string;
      export_status: string;
      included_sections: Array<Record<string, unknown>>;
      excluded_sections: Array<Record<string, unknown>>;
      missing_items: string[];
      blocked_items: string[];
      review_required_items: string[];
      evidence_map: Array<Record<string, unknown>>;
      human_review_required: boolean;
      export_allowed: boolean;
      final_export_claimed: boolean;
      submission_ready_claimed: boolean;
      download_supported: boolean;
    }>;
  };
  forms_attachments_map?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    binary_upload_supported: boolean;
    attachment_persistence_claimed: boolean;
    form_completion_claimed: boolean;
    submission_ready_claimed: boolean;
    human_review_required: boolean;
    live_ingest_claimed: boolean;
    workspaces: Array<{
      forms_attachment_map_id: string;
      application_workspace_id: string;
      opportunity_id: string;
      organization_profile_id: string;
      mapping_status: string;
      form_items: Array<Record<string, unknown>>;
      attachment_items: Array<Record<string, unknown>>;
      known_forms: Array<Record<string, unknown>>;
      likely_forms: Array<Record<string, unknown>>;
      unknown_forms: Array<Record<string, unknown>>;
      known_attachments: Array<Record<string, unknown>>;
      missing_attachments: Array<Record<string, unknown>>;
      human_review_required: boolean;
      binary_upload_supported: boolean;
      attachment_persistence_claimed: boolean;
      form_completion_claimed: boolean;
      submission_ready_claimed: boolean;
    }>;
  };
  multi_org_pilot?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    selected_organization_profile_id?: string | null;
    collaboration_enabled: boolean;
    customer_data_persistence_claimed: boolean;
    production_multi_tenant_claimed: boolean;
    live_customer_login_claimed: boolean;
    live_ingest_claimed: boolean;
    submission_ready_claimed: boolean;
    final_export_claimed: boolean;
    human_review_required: boolean;
    cohort: {
      pilot_cohort_id: string;
      cohort_label: string;
      cohort_data_mode: string;
      organization_count: number;
      organization_profile_ids: string[];
      collaboration_enabled: boolean;
      production_multi_tenant_claimed: boolean;
      live_customer_login_claimed: boolean;
    };
    organizations: Array<{
      organization_profile_id: string;
      organization_name?: string | null;
      recognition_status?: string | null;
      overall_readiness_status: string;
      opportunity_count: number;
      blockers: string[];
      qa_blocker_count: number;
      customer_actions: string[];
      operator_actions: string[];
      feedback_context_id: string;
      evidence_memory: Record<string, unknown>;
      next_safest_action: string;
      export_allowed: boolean;
      submission_ready_claimed: boolean;
      final_export_claimed: boolean;
    }>;
    operator_rollup: {
      org_count: number;
      package_count: number;
      opportunities_under_review: number;
      readiness_by_org: Record<string, string | undefined>;
      blockers_by_org: Record<string, string[]>;
      cohort_next_safest_action: string;
      production_multi_tenant_claimed: boolean;
      live_customer_login_claimed: boolean;
      collaboration_enabled: boolean;
    };
  };
  collaboration_dark_launch?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    collaboration_feature_enabled: boolean;
    collaboration_global_enabled: boolean;
    collaboration_cohort_enabled: boolean;
    organization_opt_in_required: boolean;
    data_sharing_allowed: boolean;
    partner_matching_live_claimed: boolean;
    partner_recommendations_claimed: boolean;
    fit_score_claimed: boolean;
    cohort_rollout_claimed: boolean;
    global_rollout_claimed: boolean;
    introduction_claimed: boolean;
    operator_review_required: boolean;
    consent: Record<string, unknown>;
    fit_model: {
      feature_enabled: boolean;
      fit_score_claimed: boolean;
      partner_recommendation_claimed: boolean;
      partner_names_surfaced: boolean;
      not_live_reason: string;
      dimensions: Array<Record<string, unknown>>;
    };
    rollout_controls: {
      rollout_stage: string;
      feature_exposure_status: string;
      collaboration_feature_enabled: boolean;
      collaboration_global_enabled: boolean;
      collaboration_cohort_enabled: boolean;
    };
  };
  evidence_intake?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    workspace_count: number;
    buyer_summary: string[];
    storage_modes_in_use: string[];
    storage_adapter: string;
    upload_ui_supported: boolean;
    upload_persistence_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    production_storage_claimed: boolean;
    package_unlock_claimed: boolean;
    submission_ready_claimed: boolean;
    final_export_claimed: boolean;
    migration_required: boolean;
    storage_proposal_path: string;
    human_review_required: boolean;
    workspaces: Array<{
      organization_profile_id: string;
      record_count: number;
      records: Array<Record<string, unknown>>;
      unlock_evaluation: Record<string, unknown>;
      customer_actions: string[];
      operator_actions: string[];
      upload_persistence_claimed: boolean;
      package_unlock_claimed: boolean;
      human_review_required: boolean;
      storage_adapter: string;
      upload_ui_supported: boolean;
    }>;
  };
  operator_readiness?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    monday_demo_status?: string;
    internal_pilot_status?: string;
    controlled_customer_pilot_status?: string;
    production_rollout_status?: string;
    upload_rollout_status?: string;
    collaboration_rollout_status?: string;
    live_source_rollout_status?: string;
    go_no_go_matrix: Array<Record<string, unknown>>;
    blockers: string[];
    operator_next_actions: string[];
    required_commands: string[];
    smoke_commands: string[];
    production_ready_claimed: boolean;
    pen_test_passed_claimed: boolean;
    upload_persistence_claimed: boolean;
    submission_ready_claimed: boolean;
    final_export_claimed: boolean;
    collaboration_matching_claimed: boolean;
    live_customer_login_claimed: boolean;
    contract: {
      current_head: string;
      route: string;
      production_readiness_status: string;
      upload_persistence_status: string;
      collaboration_status: string;
      multi_org_status: string;
      test_posture_reference: string;
      security_posture_reference: string;
      pen_test_readiness_reference: string;
    };
  };
  persistence_approval_gate?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    owner_approval_status: string;
    approval_scope?: string;
    approved_environment?: string;
    migration_required: boolean;
    migration_applied: boolean;
    migration_environment?: string | null;
    validated_persistent_adapter_claimed: boolean;
    validated_persistent_scope?: string | null;
    upload_persistence_claimed: boolean;
    upload_persistence_scope?: string | null;
    customer_data_persistence_claimed: boolean;
    production_storage_claimed: boolean;
    login_live_claimed?: boolean;
    controlled_customer_pilot_status?: string;
    dry_run_status: string;
    next_safe_action: string;
    approval_request_text?: string;
    storage_adapters: string[];
    what_remains_blocked_for_production?: string[];
    gate: Record<string, unknown>;
    dry_run: Record<string, unknown>;
  };
  customer_pilot_auth?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    boundary_count: number;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    rbac_enforced_claimed: boolean;
    production_multi_tenant_claimed: boolean;
    customer_data_isolation_claimed: boolean;
    controlled_customer_pilot_status: string;
    blockers: string[];
    next_safe_actions: string[];
    readiness_checklist: Record<string, unknown>;
    boundaries: Array<Record<string, unknown>>;
  };
  gate10_closeout?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    monday_demo_status: string;
    internal_pilot_status: string;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    login_live_claimed: boolean;
    production_auth_claimed: boolean;
    production_multi_tenant_claimed: boolean;
    pen_test_passed_claimed: boolean;
    sca_passed_claimed: boolean;
    final_allowed_claims: string[];
    final_forbidden_claims: string[];
    final_fallback_path: string;
  };
  national_coverage?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    top_15_count: number;
    top_15_states: Array<{ state_code: string; state_name: string }>;
    active_customer_lane: string;
    live_coverage_claimed: boolean;
    ranking_confidence_summary: string;
    what_is_live: string[];
    what_is_modeled_only: string[];
    what_needs_research: string[];
    federally_recognized_tribe_source: string;
  };
  applicant_authority?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    submission_authority_claimed: boolean;
    federal_authority_claimed: boolean;
    state_authority_claimed: boolean;
    human_review_required: boolean;
    verification_confidence: string;
    missing_evidence: string[];
    allowed_actions: string[];
    blocked_actions: string[];
    selected_person: Record<string, unknown>;
    federal_authority: Record<string, unknown>;
    state_authority: Record<string, unknown>;
  };
  evidence_lifecycle?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    audit_event_count: number;
    submission_unlock_status: boolean;
    production_policy_validated: boolean;
    legal_compliance_claimed: boolean;
    package_unlock_behavior: string;
    export_unlock_behavior: string;
  };
  top15_source_validation?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    packet_count: number;
    states_packeted: string[];
    active_customer_lane: string;
    all_top15_live_claimed: boolean;
    non_sc_live_coverage_claimed: boolean;
    sc_packet: Record<string, unknown>;
    resolutions: Array<Record<string, unknown>>;
  };
  production_enforcement?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    local_dev_persistence_validated: boolean;
    production_storage_claimed: boolean;
    customer_data_persistence_claimed: boolean;
    production_multi_tenant_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    tenant_isolation_status: string;
    blockers: string[];
    next_safe_actions: string[];
  };
  gate13_pentest_pilot?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    pen_test_passed_claimed: boolean;
    sca_passed_claimed: boolean;
    sca_run: boolean;
    login_live_claimed: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    blockers: string[];
    allowed_claims: string[];
    forbidden_claims: string[];
  };
  live_authority_spike?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    states_covered: string[];
    sam_uei_live_checked: boolean;
    sam_uei_verified_claimed: boolean;
    ebiz_poc_live_checked: boolean;
    ebiz_poc_verified_claimed: boolean;
    aor_live_checked: boolean;
    aor_verified_claimed: boolean;
    state_authority_live_checked: boolean;
    state_authority_verified_claimed: boolean;
    submit_authority: boolean;
    draft_authority: boolean;
    manage_workspace_authority: boolean;
    login_live_claimed: boolean;
    human_review_required: boolean;
  };
  sca_security_loop?: {
    schema_version: string;
    campaign_block: number;
    title: string;
    buyer_summary: string[];
    sca_run: boolean;
    sca_passed_claimed: boolean;
    npm_audit_clean?: boolean;
    pip_audit_clean?: boolean;
    high_critical_findings: string[];
    blocked_checks: string[];
    unresolved_findings: string[];
    remediated_items: string[];
    pen_test_passed_claimed: boolean;
    uv_lock_touched: boolean;
    controlled_customer_pilot_status: string;
    production_rollout_status: string;
    login_live_claimed: boolean;
    human_review_required: boolean;
  };
  nofo_showcase?: {
    schema_version: string;
    title: string;
    pack_id: string;
    selected_count: number;
    sc_selected_count: number;
    federal_selected_count: number;
    live_ingest_claimed: boolean;
    nofo_pdf_extraction_claimed: boolean;
    proposal_drafting_claimed: boolean;
    buyer_sections: string[];
    cards: Array<{
      opportunity_id: string;
      source_layer: string;
      source_name?: string | null;
      title?: string | null;
      data_mode?: string | null;
      live_ingest_claimed: boolean;
      human_review_required: boolean;
      field_status_counts: Record<string, number>;
      unresolved_fields: string[];
      what_nativeforge_found: Record<string, unknown>;
      what_this_means?: string | null;
      what_is_missing: Array<Record<string, unknown>>;
      what_needs_human_review: string[];
      what_to_do_next: string[];
      application_plan: {
        recommendation_label?: string;
        application_checklist?: Array<Record<string, unknown>>;
        narrative_section_scaffold?: Array<Record<string, unknown>>;
        forms_checklist?: Array<Record<string, unknown>>;
        attachment_checklist?: Array<Record<string, unknown>>;
        missing_information_questions?: Array<Record<string, unknown>>;
        completeness?: Record<string, unknown>;
        proposal_drafting_claimed: boolean;
        nofo_pdf_extraction_claimed: boolean;
      };
      evidence_provenance: Record<string, unknown>;
      limitations: string[];
    }>;
  };
};
