import { describe, expect, it } from "vitest";

import { loadScCustomerDemoPayload } from "../demo/loadScCustomerDemo";
import { ScCustomerDemoPage } from "./ScCustomerDemoPage";
import { renderToStaticMarkup } from "react-dom/server";

describe("ScCustomerDemoPage", () => {
  it("renders buyer story and honest flags from static payload", () => {
    const payload = loadScCustomerDemoPayload();
    const html = renderToStaticMarkup(<ScCustomerDemoPage payload={payload} />);
    expect(html).toContain("sc-customer-demo-page");
    expect(html).toContain("live_ingestion=false");
    expect(html).toContain("final_eligibility_claim_allowed=false");
    expect(html).toContain("live_ingest_claimed=false");
    expect(html).toContain("What NativeForge found");
    expect(html).toContain("south_carolina=");
    expect(html).toContain("federal=");
    expect(html).toContain("nofo_pdf_extraction=NOT_SUPPORTED");
    expect(html).toContain("sc-demo-nofo-showcase");
    expect(html).toContain("What NativeForge found");
    expect(html).toContain("Application plan skeleton");
    expect(html).toContain("live_ingest_claimed=false");
    expect(html).toContain("nofo_pdf_extraction_claimed=false");
    expect(html).toContain("proposal_drafting_claimed=false");
    expect(html).toContain("sc-demo-opening-line");
    expect(html).toContain("sc-demo-closing-line");
    expect(html).toContain("sc-demo-trust-strip");
    expect(html).toContain("curated-current");
    expect(html).toContain("not automated live ingest");
    expect(html).toContain("Forbidden claims");
    expect(html).toContain("sc-demo-opportunity-engine");
    expect(html).toContain("Durable opportunity engine foundation");
    expect(html).toContain("org_geo_filters_federal=false");
    expect(html).toContain("sc-demo-eligibility-evidence");
    expect(html).toContain("final_eligibility_claimed=false");
    expect(html).toContain("Evidence-backed eligibility");
    expect(html).toContain("sc-demo-pursuit-workspace");
    expect(html).toContain("Pursuit workspace / application package");
    expect(html).toContain("submission_ready_claimed=false");
    expect(html).toContain("proposal_drafting_claimed=false");
    expect(html).toContain("not_submission_ready=");
    expect(html).toContain("sc-demo-application-checklist");
    expect(html).toContain("Application checklist / package build plan");
    expect(html).toContain("submission_allowed=false");
    expect(html).toContain("application_complete_claimed=false");
    expect(html).toContain("sc-demo-intake-approvals");
    expect(html).toContain("Intake &amp; approvals / package gaps");
    expect(html).toContain("upload_persistence_claimed=false");
    expect(html).toContain("approval_persistence_claimed=false");
    expect(html).toContain("package_readiness_unlocked=false");
    expect(html).toContain("sc-demo-narrative-budget");
    expect(html).toContain("Narrative &amp; budget scaffold");
    expect(html).toContain("generated_prose_produced=false");
    expect(html).toContain("drafting_supported=false");
    expect(html).toContain("budget_claimed_complete=false");
    expect(html).toContain("match_claimed_complete=false");
    expect(html).toContain("sc-demo-readiness-queue");
    expect(html).toContain("Readiness &amp; review queue");
    expect(html).toContain("submission_ready_claimed=false");
    expect(html).toContain("final_eligibility_claimed=false");
    expect(html).toContain("not_submission_ready=true");
    expect(html).toContain("sc-demo-org-evidence-memory");
    expect(html).toContain("Organization evidence memory");
    expect(html).toContain("customer_data_persistence_claimed=false");
    expect(html).toContain("binary_upload_persistence_supported=false");
    expect(html).toContain("None auto-approved without review.");
    expect(html).toContain("Must not claim");
    expect(html).toContain("sc-demo-nofo-extraction-pilot");
    expect(html).toContain("NOFO extraction pilot");
    expect(html).toContain("full_pdf_extraction_claimed=false");
    expect(html).toContain("broad_pdf_support_claimed=false");
    expect(html).toContain("pdf_bytes_parsed=false");
    expect(html).toContain("sc-demo-source-freshness");
    expect(html).toContain("Source freshness / source health");
    expect(html).toContain("external_live_check_not_run=true");
    expect(html).toContain("continuous_monitoring_claimed=false");
    expect(html).toContain("production_activation_claimed=false");
    expect(html).toContain("sc-demo-draft-workspace");
    expect(html).toContain("Draft workspace (human-authored)");
    expect(html).toContain("ai_drafting_enabled=false");
    expect(html).toContain("generated_prose_present=false");
    expect(html).toContain("customer_prose_persistence_claimed=false");
    expect(html).toContain("sc-demo-controlled-drafting");
    expect(html).toContain("Controlled draft v0");
    expect(html).toContain("complete_proposal_claimed=false");
    expect(html).toContain("sc-demo-ai-governance");
    expect(html).toContain("AI governance / QA gates");
    expect(html).toContain("qa_passed=false");
    expect(html).toContain("export_allowed=false");
    expect(html).toContain("submission_allowed=false");
    expect(html).toContain("sc-demo-feedback-loop");
    expect(html).toContain("sc-demo-package-export-preview");
    expect(html).toContain("sc-demo-forms-attachments-map");
    expect(html).toContain("sc-demo-multi-org-pilot");
    expect(html).toContain("sc-demo-collaboration-dark-launch");
    expect(html).toContain("sc-demo-evidence-intake");
    expect(html).toContain("sc-demo-operator-readiness");
    expect(html).toContain("sc-demo-persistence-approval-gate");
    expect(html).toContain("sc-demo-customer-pilot-auth");
    expect(html).toContain("sc-demo-gate10-closeout");
    expect(html).toContain("sc-demo-national-coverage");
    expect(html).toContain("sc-demo-applicant-authority");
    expect(html).toContain("sc-demo-evidence-lifecycle");
    expect(html).toContain("sc-demo-top15-source-validation");
    expect(html).toContain("sc-demo-production-enforcement");
    expect(html).toContain("sc-demo-gate13-pentest-pilot");
    expect(html).toContain("sc-demo-live-authority-spike");
    expect(html).toContain("sc-demo-sca-security-loop");
    expect(html).toContain("sc-demo-rbac-enforcement");
    expect(html).toContain("sc-demo-audit-operator-storage");
    expect(html).toContain("sc-demo-external-pilot-auth");
    expect(html).toContain("sc-demo-storage-sca-pentest");
    expect(html).toContain("sc-demo-oidc-live-path");
    expect(html).toContain("sc-demo-storage-pentest-support");
    expect(html).toContain("sc-demo-auth0-validation");
    expect(html).toContain("sc-demo-storage-feature-flags");
    expect(html).toContain("sc-demo-auth0-live-validation");
    expect(html).toContain("sc-demo-storage-pilot-gate");
    expect(html).toContain("sc-demo-auth0-mode-b");
    expect(html).toContain("sc-demo-gate20-closeout");
    expect(html).toContain("sc-demo-auth0-mode-b-live-unlock");
    expect(html).toContain("sc-demo-gate21-storage-pilot");
    expect(html).toContain("sc-demo-production-metadata");
    expect(html).toContain("sc-demo-object-storage-signed-url");
    expect(html).toContain("sc-demo-customer-data-policy");
    expect(html).toContain("sc-demo-retention-delete-export");
    expect(html).toContain("sc-demo-auth0-login-rbac");
    expect(html).toContain("sc-demo-session-tenant");
    expect(html).toContain("sc-demo-storage-approval-metadata");
    expect(html).toContain("sc-demo-object-storage-unlock");
    expect(html).toContain("sc-demo-security-attestation");
    expect(html).toContain("sc-demo-controlled-pilot-master");
    expect(html).toContain("sc-demo-owner-unlock-packet");
    expect(html).toContain("sc-demo-cutover-claim-freeze");
    expect(html).toContain("sc-demo-mode-b-rehearsal");
    expect(html).toContain("sc-demo-dry-run-cutover");
    expect(html).toContain("sc-demo-auth0-real-input");
    expect(html).toContain("sc-demo-storage-security-real-input");
    expect(html).toContain("sc-demo-operator-command-center");
    expect(html).toContain("sc-demo-final-closeout");
    expect(html).toContain("sc-demo-buyer-trust-views");
    expect(html).toContain("sc-demo-live-authority-execution");
    expect(html).toContain("sc-demo-live-source-coverage");
    expect(html).toContain("sc-demo-pilot-org-onboarding");
    expect(html).toContain("sc-demo-support-triage");
    expect(html).toContain("sc-demo-gate32-source-freshness");
    expect(html).toContain("sc-demo-gate32-observability");
    expect(html).toContain("sc-demo-backup-restore");
    expect(html).toContain("sc-demo-launch-packet");
    expect(html).toContain("sc-demo-gate33-source-probes");
    expect(html).toContain("sc-demo-gate33-healthchecks");
    expect(html).toContain("sc-demo-gate33-restore");
    expect(html).toContain("sc-demo-gate33-runbooks");
    expect(html).toContain("sc-demo-gate34-owner-wait");
    expect(html).toContain("sc-demo-gate34-talk-track");
    expect(html).toContain("sc-demo-gate34-drill");
    expect(html).toContain("sc-demo-gate34-closeout");
    expect(html).toContain("Customer feedback / reporting");
    expect(html).toContain("slack_live_sent_claimed=false");
    expect(html).toContain("collaboration_feature_enabled=false");
    expect(payload.buyer_demo?.opening_line).toBeTruthy();
    expect(payload.pursuit_workspace?.workspace_count).toBeGreaterThanOrEqual(1);
    expect(payload.pursuit_workspace?.final_submission_allowed).toBe(false);
    expect(payload.pursuit_workspace?.proposal_drafting_claimed).toBe(false);
    expect(
      payload.application_plan_workspace?.workspace_count,
    ).toBeGreaterThanOrEqual(1);
    expect(payload.application_plan_workspace?.submission_allowed).toBe(false);
    expect(payload.application_plan_workspace?.proposal_drafting_claimed).toBe(
      false,
    );
    expect(payload.application_plan_workspace?.application_complete_claimed).toBe(
      false,
    );
    expect(
      payload.intake_approval_workspace?.workspace_count,
    ).toBeGreaterThanOrEqual(1);
    expect(
      payload.intake_approval_workspace?.binary_upload_persistence_claimed,
    ).toBe(false);
    expect(payload.intake_approval_workspace?.approval_persistence_claimed).toBe(
      false,
    );
    expect(payload.intake_approval_workspace?.package_readiness_unlocked).toBe(
      false,
    );
    expect(
      payload.narrative_budget_scaffold?.workspace_count,
    ).toBeGreaterThanOrEqual(1);
    expect(payload.narrative_budget_scaffold?.generated_prose_produced).toBe(false);
    expect(payload.narrative_budget_scaffold?.drafting_supported).toBe(false);
    expect(payload.narrative_budget_scaffold?.budget_claimed_complete).toBe(false);
    expect(payload.narrative_budget_scaffold?.match_claimed_complete).toBe(false);
    expect(
      payload.package_readiness_queue?.workspace_count,
    ).toBeGreaterThanOrEqual(1);
    expect(payload.package_readiness_queue?.submission_ready_claimed).toBe(false);
    expect(payload.package_readiness_queue?.final_eligibility_claimed).toBe(false);
    expect(payload.package_readiness_queue?.not_submission_ready_label).toBe(true);
    expect(
      payload.organization_evidence_memory?.profile_count,
    ).toBeGreaterThanOrEqual(1);
    expect(payload.organization_evidence_memory?.federal_count).toBeGreaterThanOrEqual(
      1,
    );
    expect(
      payload.organization_evidence_memory?.state_only_count,
    ).toBeGreaterThanOrEqual(1);
    expect(
      payload.organization_evidence_memory?.customer_data_persistence_claimed,
    ).toBe(false);
    expect(payload.organization_evidence_memory?.final_eligibility_claimed).toBe(
      false,
    );
    expect(payload.organization_evidence_memory?.fabricated_org_facts).toBe(false);
    expect(payload.nofo_extraction_pilot?.pilot_opportunity_id).toBe("la-real-006");
    expect(payload.nofo_extraction_pilot?.full_pdf_extraction_claimed).toBe(false);
    expect(payload.nofo_extraction_pilot?.broad_pdf_support_claimed).toBe(false);
    expect(payload.nofo_extraction_pilot?.pdf_bytes_parsed).toBe(false);
    expect(payload.source_freshness_pilot?.source_count).toBeGreaterThanOrEqual(1);
    expect(payload.source_freshness_pilot?.live_ingest_claimed).toBe(false);
    expect(payload.source_freshness_pilot?.continuous_monitoring_claimed).toBe(false);
    expect(payload.source_freshness_pilot?.production_activation_claimed).toBe(false);
    expect(payload.source_freshness_pilot?.external_live_check_not_run).toBe(true);
    expect(payload.draft_workspace?.workspace_count).toBeGreaterThanOrEqual(1);
    expect(payload.draft_workspace?.ai_drafting_enabled).toBe(false);
    expect(payload.draft_workspace?.generated_prose_present).toBe(false);
    expect(payload.draft_workspace?.customer_prose_persistence_claimed).toBe(false);
    expect(payload.controlled_drafting?.workspace_count).toBeGreaterThanOrEqual(1);
    expect(payload.controlled_drafting?.complete_proposal_claimed).toBe(false);
    expect(payload.controlled_drafting?.submission_ready_claimed).toBe(false);
    expect(payload.controlled_drafting?.final_text_claimed).toBe(false);
    expect(payload.ai_governance?.qa_passed).toBe(false);
    expect(payload.ai_governance?.export_allowed).toBe(false);
    expect(payload.ai_governance?.submission_allowed).toBe(false);
    expect(payload.feedback_loop?.report_hook_count).toBeGreaterThanOrEqual(10);
    expect(payload.feedback_loop?.slack_live_sent_claimed).toBe(false);
    expect(payload.feedback_loop?.persistence_claimed).toBe(false);
    expect(
      payload.feedback_loop?.collaboration.collaboration_feature_enabled,
    ).toBe(false);
    expect(payload.package_export_preview?.export_allowed).toBe(false);
    expect(payload.package_export_preview?.final_export_claimed).toBe(false);
    expect(payload.package_export_preview?.submission_ready_claimed).toBe(false);
    expect(payload.package_export_preview?.download_supported).toBe(false);
    expect(payload.forms_attachments_map?.binary_upload_supported).toBe(false);
    expect(payload.forms_attachments_map?.attachment_persistence_claimed).toBe(
      false,
    );
    expect(payload.forms_attachments_map?.form_completion_claimed).toBe(false);
    expect(payload.forms_attachments_map?.submission_ready_claimed).toBe(false);
    expect(payload.multi_org_pilot?.cohort.organization_count).toBeGreaterThanOrEqual(
      4,
    );
    expect(payload.multi_org_pilot?.production_multi_tenant_claimed).toBe(false);
    expect(payload.multi_org_pilot?.live_customer_login_claimed).toBe(false);
    expect(payload.multi_org_pilot?.collaboration_enabled).toBe(false);
    expect(
      payload.collaboration_dark_launch?.collaboration_feature_enabled,
    ).toBe(false);
    expect(payload.collaboration_dark_launch?.data_sharing_allowed).toBe(false);
    expect(
      payload.collaboration_dark_launch?.partner_matching_live_claimed,
    ).toBe(false);
    expect(
      payload.collaboration_dark_launch?.partner_recommendations_claimed,
    ).toBe(false);
    expect(payload.evidence_intake?.upload_persistence_claimed).toBe(false);
    expect(payload.evidence_intake?.package_unlock_claimed).toBe(false);
    expect(payload.evidence_intake?.upload_ui_supported).toBe(false);
    expect(payload.operator_readiness?.production_ready_claimed).toBe(false);
    expect(payload.operator_readiness?.pen_test_passed_claimed).toBe(false);
    expect(payload.operator_readiness?.monday_demo_status).toBe("GO");
    expect(payload.operator_readiness?.production_rollout_status).toBe("NO_GO");
    expect(payload.persistence_approval_gate?.migration_applied).toBe(true);
    expect(payload.persistence_approval_gate?.upload_persistence_scope).toBe(
      "local_dev_only",
    );
    expect(
      payload.persistence_approval_gate?.validated_persistent_scope,
    ).toBe("local_dev_only");
    expect(payload.persistence_approval_gate?.production_storage_claimed).toBe(
      false,
    );
    expect(
      payload.persistence_approval_gate?.customer_data_persistence_claimed,
    ).toBe(false);
    expect(payload.customer_pilot_auth?.login_live_claimed).toBe(false);
    expect(payload.customer_pilot_auth?.production_auth_claimed).toBe(false);
    expect(payload.customer_pilot_auth?.controlled_customer_pilot_status).toBe(
      "NO_GO",
    );
    expect(payload.gate10_closeout?.monday_demo_status).toBe("GO");
    expect(payload.gate10_closeout?.pen_test_passed_claimed).toBe(false);
    expect(payload.national_coverage?.top_15_count).toBe(15);
    expect(payload.national_coverage?.live_coverage_claimed).toBe(false);
    expect(payload.national_coverage?.active_customer_lane).toBe("SC");
    expect(payload.applicant_authority?.submission_authority_claimed).toBe(false);
    expect(payload.applicant_authority?.federal_authority_claimed).toBe(false);
    expect(payload.evidence_lifecycle?.submission_unlock_status).toBe(false);
    expect(payload.evidence_lifecycle?.legal_compliance_claimed).toBe(false);
    expect(payload.top15_source_validation?.packet_count).toBe(15);
    expect(payload.top15_source_validation?.all_top15_live_claimed).toBe(false);
    expect(payload.production_enforcement?.production_storage_claimed).toBe(false);
    expect(payload.production_enforcement?.controlled_customer_pilot_status).toBe(
      "NO_GO",
    );
    expect(payload.gate13_pentest_pilot?.pen_test_passed_claimed).toBe(false);
    expect(payload.gate13_pentest_pilot?.sca_passed_claimed).toBe(false);
    expect(payload.live_authority_spike?.sam_uei_verified_claimed).toBe(false);
    expect(payload.live_authority_spike?.submit_authority).toBe(false);
    expect(payload.live_authority_spike?.states_covered?.length).toBe(15);
    expect(payload.sca_security_loop?.pen_test_passed_claimed).toBe(false);
    expect(payload.sca_security_loop?.controlled_customer_pilot_status).toBe(
      "NO_GO",
    );
    expect(payload.rbac_enforcement?.login_live_claimed).toBe(false);
    expect(payload.rbac_enforcement?.rbac_enforced_claimed).toBe(true);
    expect(payload.rbac_enforcement?.controlled_customer_pilot_status).toBe(
      "NO_GO",
    );
    expect(payload.audit_operator_storage?.production_storage_claimed).toBe(
      false,
    );
    expect(payload.audit_operator_storage?.controlled_customer_pilot_status).toBe(
      "NO_GO",
    );
    expect(payload.external_pilot_auth?.login_live_claimed).toBe(false);
    expect(payload.external_pilot_auth?.invite_status).not.toBe("sent");
    expect(payload.storage_sca_pentest?.production_storage_approved).toBe(false);
    expect(payload.storage_sca_pentest?.pen_test_passed_claimed).toBe(false);
    expect(payload.oidc_live_path?.login_live_claimed).toBe(false);
    expect(payload.oidc_live_path?.provider_configured).toBe(false);
    expect(payload.storage_pentest_support?.production_storage_claimed).toBe(
      false,
    );
    expect(payload.storage_pentest_support?.pen_test_passed_claimed).toBe(false);
    expect(payload.auth0_validation?.login_live_claimed).toBe(false);
    expect(payload.auth0_validation?.controlled_pilot_auth_ready).toBe(false);
    expect(payload.storage_feature_flags?.production_storage_enabled).toBe(false);
    expect(payload.storage_feature_flags?.production_storage_claimed).toBe(false);
    expect(payload.auth0_live_validation?.login_live_claimed).toBe(false);
    expect(payload.auth0_live_validation?.validation_possible).toBe(false);
    expect(payload.storage_pilot_gate?.real_provisioning_allowed).toBe(false);
    expect(payload.storage_pilot_gate?.controlled_customer_pilot_status).not.toBe(
      "CONTROLLED_CUSTOMER_GO",
    );
    expect(payload.auth0_mode_b?.mode_detected).toBe("mode_a");
    expect(payload.auth0_mode_b?.login_live_claimed).toBe(false);
    expect(payload.gate20_closeout?.pen_test_passed_claim).toBe(false);
    expect(payload.gate20_closeout?.production_storage_claimed).toBe(false);
    expect(payload.auth0_mode_b_live_unlock?.login_live_claimed).toBe(false);
    expect(payload.auth0_mode_b_live_unlock?.mode_detected).toBe("mode_a");
    expect(payload.gate21_storage_pilot?.owner_storage_approval_present).toBe(false);
    expect(payload.gate21_storage_pilot?.production_storage_claimed).toBe(false);
    expect(payload.production_metadata?.production_metadata_writes_allowed).toBe(
      false,
    );
    expect(payload.production_metadata?.production_storage_claimed).toBe(false);
    expect(payload.object_storage_signed_url?.production_writes_allowed).toBe(false);
    expect(payload.object_storage_signed_url?.fake_upload_ui_exposed).toBe(false);
    expect(payload.customer_data_policy?.customer_data_persistence_claimed).toBe(
      false,
    );
    expect(payload.customer_data_policy?.ai_training_consent_default).toBe(false);
    expect(payload.retention_delete_export?.final_export_claimed).toBe(false);
    expect(payload.retention_delete_export?.fake_production_export_ui).toBe(false);
    expect(payload.auth0_login_rbac?.login_live_claimed).toBe(false);
    expect(payload.auth0_login_rbac?.fake_login_ui).toBe(false);
    expect(payload.session_tenant_enforcement?.production_multi_tenant_claimed).toBe(
      false,
    );
    expect(payload.session_tenant_enforcement?.fake_customer_access_ui).toBe(false);
    expect(payload.storage_approval_metadata?.production_storage_claimed).toBe(false);
    expect(payload.storage_approval_metadata?.fake_upload_ui).toBe(false);
    expect(payload.object_storage_unlock?.signed_urls_live).toBe(false);
    expect(payload.object_storage_unlock?.fake_signed_url_ui).toBe(false);
    expect(payload.security_attestation?.pen_test_passed).toBe(false);
    expect(payload.security_attestation?.fake_secure_badge).toBe(false);
    expect(payload.controlled_pilot_master?.fake_pilot_ready_banner).toBe(false);
    expect(
      payload.controlled_pilot_master?.controlled_customer_pilot_status,
    ).not.toBe("CONTROLLED_CUSTOMER_GO");
    expect(payload.owner_unlock_packet?.mode_b_executed).toBe(false);
    expect(payload.owner_unlock_packet?.fake_mode_b).toBe(false);
    expect(payload.cutover_claim_freeze?.fake_production_ready).toBe(false);
    expect(payload.cutover_claim_freeze?.fake_pilot_ready).toBe(false);
    expect(payload.mode_b_rehearsal?.mode_b_executed_claimed).toBe(false);
    expect(payload.mode_b_rehearsal?.fake_mode_b).toBe(false);
    expect(payload.mode_b_rehearsal?.synthetic_fixture_used).toBe(true);
    expect(payload.dry_run_cutover?.production_cutover_executed).toBe(false);
    expect(payload.dry_run_cutover?.fake_cutover_complete).toBe(false);
    expect(payload.dry_run_cutover?.first_hard_blocker).toBe("auth0_oidc_preflight");
    expect(payload.auth0_real_input?.login_live_claimed).toBe(false);
    expect(payload.auth0_real_input?.synthetic_rehearsal_artifacts_ignored).toBe(
      true,
    );
    expect(payload.storage_security_real_input?.production_storage_claimed).toBe(
      false,
    );
    expect(payload.storage_security_real_input?.pen_test_pass_claimed).toBe(false);
    expect(payload.storage_security_real_input?.fake_pilot_ready).toBe(false);
    expect(payload.final_closeout?.fake_production_ready).toBe(false);
    expect(payload.final_closeout?.fake_pilot_ready).toBe(false);
    expect(payload.final_closeout?.login_live_claimed).toBe(false);
    expect(payload.buyer_trust?.fake_green_badge).toBe(false);
    expect(payload.buyer_trust?.login_live_claimed).toBe(false);
    expect(payload.buyer_trust?.pen_test_passed_claimed).toBe(false);
    expect(payload.buyer_trust?.production_storage_claimed).toBe(false);
    expect(payload.buyer_trust?.blockers_exposed).toBe(true);
    expect(
      payload.buyer_trust?.controlled_customer_pilot_status,
    ).not.toBe("CONTROLLED_CUSTOMER_GO");
    expect(payload.live_authority_execution?.can_submit).toBe(false);
    expect(payload.live_authority_execution?.final_eligibility_claim).toBe(false);
    expect(payload.live_source_coverage?.top15_live_claimed).toBe(false);
    expect(payload.live_source_coverage?.broad_coverage_claimed).toBe(false);
    expect(payload.pilot_org_onboarding?.invite_sent_claimed).toBe(false);
    expect(payload.pilot_org_onboarding?.customer_access_claim).toBe(false);
    expect(payload.support_triage?.slack_sent_claimed).toBe(false);
    expect(payload.source_freshness?.live_source_claim).toBe(false);
    expect(payload.observability?.alert_sent_claimed).toBe(false);
    expect(payload.backup_restore?.production_restore_claimed).toBe(false);
    expect(payload.launch_packet?.controlled_customer_pilot_status).not.toBe(
      "CONTROLLED_CUSTOMER_GO",
    );
    expect(payload.source_probes?.live_source_claim).toBe(false);
    expect(payload.healthchecks?.alert_sent_claimed).toBe(false);
    expect(payload.restore_rehearsal?.production_restore_claimed).toBe(false);
    expect(payload.operator_runbooks?.controlled_customer_pilot_status).not.toBe(
      "CONTROLLED_CUSTOMER_GO",
    );
    expect(payload.owner_wait?.live_claims_unlocked).toBe(false);
    expect(payload.talk_track?.cta_safe).toBe(true);
    expect(payload.operator_drill?.pilot_go_claimed).toBe(false);
    expect(payload.pre_owner_closeout?.controlled_customer_pilot_status).not.toBe(
      "CONTROLLED_CUSTOMER_GO",
    );
    expect(payload.opportunity_engine?.combined_workflow.counts.sc_state).toBeGreaterThanOrEqual(
      1,
    );
    expect(
      payload.opportunity_engine?.combined_workflow.counts.federal,
    ).toBeGreaterThanOrEqual(1);
    expect(
      payload.opportunity_engine?.combined_workflow.eligibility_evidence_handoff
        ?.federal_pairs_visible,
    ).toBe(true);
    expect(
      payload.opportunity_engine?.combined_workflow.eligibility_evidence_handoff
        ?.final_eligibility_claimed,
    ).toBe(false);
    expect(payload.nofo_showcase?.sc_selected_count).toBeGreaterThanOrEqual(1);
    expect(payload.nofo_showcase?.federal_selected_count).toBeGreaterThanOrEqual(1);
    expect(payload.opportunities.south_carolina_count).toBeGreaterThanOrEqual(1);
    expect(payload.opportunities.federal_count).toBeGreaterThanOrEqual(1);
  });

  it("renders loading empty and error states", () => {
    expect(renderToStaticMarkup(<ScCustomerDemoPage loading />)).toContain(
      "sc-demo-loading",
    );
    expect(
      renderToStaticMarkup(<ScCustomerDemoPage error="boom" payload={null} />),
    ).toContain("sc-demo-error");
    expect(renderToStaticMarkup(<ScCustomerDemoPage payload={null} />)).toContain(
      "sc-demo-empty",
    );
  });
});
