"""Deterministic Discovery Engine seed catalog for opportunity sources (illustrative rows).

Rows are inserted per plane (demo vs real) with stable UUIDs from :func:`catalog_source_row_id`.
"""

from __future__ import annotations

import uuid
from typing import Any

from nativeforge.domain.enums import (
    ExpectedOpportunityFrequency,
    FundingDomain,
    OpportunitySourceType,
    OpportunityVerificationStatus,
    SourceCheckMethod,
    SourcePriorityLevel,
    SourceReliabilityRating,
)

_CATALOG_NS = uuid.uuid5(
    uuid.NAMESPACE_URL,
    "https://nativeforge.dev/nf/opportunity-source-catalog/v1",
)


def catalog_source_row_id(*, catalog_key: str, is_demo: bool) -> uuid.UUID:
    """Stable primary key for a catalog definition within demo or real plane."""
    plane = "demo" if is_demo else "real"
    return uuid.uuid5(_CATALOG_NS, f"{plane}:{catalog_key}")


# Representative Native-relevant coverage across the source universe (illustrative).
OPPORTUNITY_SOURCE_SEED_CATALOG: list[dict[str, Any]] = [
    {
        "catalog_key": "nf-catalog-federal-tribal-programs",
        "source_name": "Federal tribal programs portal (illustrative)",
        "source_type": OpportunitySourceType.federal.value,
        "publisher_name": "Illustrative federal agency",
        "source_url": "https://example.gov/nf-catalog/federal-tribal-programs",
        "description": (
            "Catalog placeholder for federal announcements commonly relevant to "
            "federally recognized tribes and Native organizations."
        ),
        "geographic_scope_json": {"label": "national", "notes": "United States"},
        "funding_domains_json": [
            FundingDomain.governance.value,
            FundingDomain.climate_resilience.value,
            FundingDomain.infrastructure.value,
        ],
        "applicant_types_json": ["federally_recognized_tribe", "tribal_organization"],
        "covered_states_json": None,
        "covered_regions_json": [{"id": "national_us", "label": "United States"}],
        "covered_tribal_groups_json": None,
        "coverage_notes": "Broad federal coverage; refine per agency in production.",
        "native_relevance_notes": "Explicit tribal eligibility or set-asides are common.",
        "reliability_rating": SourceReliabilityRating.medium.value,
        "verification_status": OpportunityVerificationStatus.operator_reviewed.value,
        "freshness_interval_days": 14,
        "check_method": SourceCheckMethod.web_page.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.monthly.value,
        "priority_level": SourcePriorityLevel.high.value,
    },
    {
        "catalog_key": "nf-catalog-state-rural-development",
        "source_name": "State rural development opportunities (illustrative)",
        "source_type": OpportunitySourceType.state.value,
        "publisher_name": "Illustrative state economic development office",
        "source_url": "https://example.org/nf-catalog/state-rural-dev",
        "description": "Catalog placeholder for state-administered rural and community funds.",
        "geographic_scope_json": {"label": "single_state", "state_code": "OK"},
        "funding_domains_json": [
            FundingDomain.economic_development.value,
            FundingDomain.broadband.value,
            FundingDomain.infrastructure.value,
        ],
        "applicant_types_json": ["local_government", "nonprofit", "tribe"],
        "covered_states_json": ["OK"],
        "covered_regions_json": [{"id": "southwest", "label": "Southwest"}],
        "covered_tribal_groups_json": None,
        "coverage_notes": "Swap state_code for operator deployments.",
        "native_relevance_notes": "Many states publish tribal consultation requirements.",
        "reliability_rating": SourceReliabilityRating.medium.value,
        "verification_status": OpportunityVerificationStatus.unverified.value,
        "freshness_interval_days": 30,
        "check_method": SourceCheckMethod.manual.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.quarterly.value,
        "priority_level": SourcePriorityLevel.medium.value,
    },
    {
        "catalog_key": "nf-catalog-tribal-consortium",
        "source_name": "Intertribal consortium funding bulletin (illustrative)",
        "source_type": OpportunitySourceType.tribal.value,
        "publisher_name": "Illustrative regional tribal consortium",
        "source_url": "https://example.org/nf-catalog/tribal-consortium",
        "description": "Placeholder for consortium-issued funding and partnership notices.",
        "geographic_scope_json": {"label": "multi_state", "notes": "Pacific Northwest"},
        "funding_domains_json": [
            FundingDomain.health.value,
            FundingDomain.education.value,
            FundingDomain.language_culture.value,
        ],
        "applicant_types_json": ["tribe", "tribal_nonprofit"],
        "covered_states_json": ["WA", "OR", "ID"],
        "covered_regions_json": [
            {"id": "pacific_northwest", "label": "Pacific Northwest"}
        ],
        "covered_tribal_groups_json": ["confederated_placeholder"],
        "coverage_notes": "Replace consortium name with live publisher when known.",
        "native_relevance_notes": "Often tribally governed eligibility.",
        "reliability_rating": SourceReliabilityRating.high.value,
        "verification_status": OpportunityVerificationStatus.trusted.value,
        "freshness_interval_days": 21,
        "check_method": SourceCheckMethod.email_newsletter.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.monthly.value,
        "priority_level": SourcePriorityLevel.critical.value,
    },
    {
        "catalog_key": "nf-catalog-national-foundation",
        "source_name": "National foundation Native-led funding (illustrative)",
        "source_type": OpportunitySourceType.foundation.value,
        "publisher_name": "Illustrative national foundation",
        "source_url": "https://example.org/nf-catalog/foundation-native-led",
        "description": "Placeholder for philanthropic opportunities prioritizing Native communities.",
        "geographic_scope_json": {"label": "national"},
        "funding_domains_json": [
            FundingDomain.language_culture.value,
            FundingDomain.education.value,
            FundingDomain.justice.value,
        ],
        "applicant_types_json": ["native_led_nonprofit", "tribe"],
        "covered_states_json": None,
        "covered_regions_json": [{"id": "national_us", "label": "United States"}],
        "covered_tribal_groups_json": None,
        "coverage_notes": "Foundation cycles vary; monitor LOI windows.",
        "native_relevance_notes": "Explicit Native-led or Native-serving priorities.",
        "reliability_rating": SourceReliabilityRating.medium.value,
        "verification_status": OpportunityVerificationStatus.operator_reviewed.value,
        "freshness_interval_days": 45,
        "check_method": SourceCheckMethod.web_page.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.quarterly.value,
        "priority_level": SourcePriorityLevel.high.value,
    },
    {
        "catalog_key": "nf-catalog-native-nonprofit-network",
        "source_name": "Native nonprofit capacity network (illustrative)",
        "source_type": OpportunitySourceType.nonprofit.value,
        "publisher_name": "Illustrative intermediary nonprofit",
        "source_url": "https://example.org/nf-catalog/native-nonprofit-network",
        "description": "Placeholder for subgrant and partnership RFAs distributed by intermediaries.",
        "geographic_scope_json": {"label": "national"},
        "funding_domains_json": [
            FundingDomain.workforce.value,
            FundingDomain.economic_development.value,
            FundingDomain.housing.value,
        ],
        "applicant_types_json": ["native_serving_nonprofit", "cdc"],
        "covered_states_json": None,
        "covered_regions_json": None,
        "covered_tribal_groups_json": None,
        "coverage_notes": "Intermediaries often mirror federal domains with lighter burden.",
        "native_relevance_notes": "Native-serving intermediaries common in this lane.",
        "reliability_rating": SourceReliabilityRating.medium.value,
        "verification_status": OpportunityVerificationStatus.unverified.value,
        "freshness_interval_days": 30,
        "check_method": SourceCheckMethod.partner_feed.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.irregular.value,
        "priority_level": SourcePriorityLevel.medium.value,
    },
    {
        "catalog_key": "nf-catalog-tribal-college-sponsored-programs",
        "source_name": "Tribal college sponsored programs office (illustrative)",
        "source_type": OpportunitySourceType.university.value,
        "publisher_name": "Illustrative tribal college",
        "source_url": "https://example.edu/nf-catalog/tc-sponsored-programs",
        "description": "Placeholder for RFAs issued through tribal college research offices.",
        "geographic_scope_json": {"label": "institution_and_partners"},
        "funding_domains_json": [
            FundingDomain.education.value,
            FundingDomain.workforce.value,
            FundingDomain.language_culture.value,
        ],
        "applicant_types_json": ["tribal_college", "partner_districts"],
        "covered_states_json": ["MT"],
        "covered_regions_json": [{"id": "northern_plains", "label": "Northern Plains"}],
        "covered_tribal_groups_json": None,
        "coverage_notes": "Partner match rules vary by opportunity.",
        "native_relevance_notes": "Tribal institution-led applicants and partners.",
        "reliability_rating": SourceReliabilityRating.medium.value,
        "verification_status": OpportunityVerificationStatus.unverified.value,
        "freshness_interval_days": 60,
        "check_method": SourceCheckMethod.pdf_bulletin.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.annual.value,
        "priority_level": SourcePriorityLevel.medium.value,
    },
    {
        "catalog_key": "nf-catalog-corporate-community-grants",
        "source_name": "Corporate community grants portal (illustrative)",
        "source_type": OpportunitySourceType.corporate.value,
        "publisher_name": "Illustrative corporation CSR office",
        "source_url": "https://example.com/nf-catalog/community-grants",
        "description": "Placeholder for CSR and community investment announcements.",
        "geographic_scope_json": {
            "label": "multi_state",
            "notes": "US operating areas",
        },
        "funding_domains_json": [
            FundingDomain.energy.value,
            FundingDomain.workforce.value,
            FundingDomain.infrastructure.value,
        ],
        "applicant_types_json": ["nonprofit", "tribe", "school_district"],
        "covered_states_json": None,
        "covered_regions_json": None,
        "covered_tribal_groups_json": None,
        "coverage_notes": "Geography often tied to facilities footprint.",
        "native_relevance_notes": "Look for Indigenous community partnership language.",
        "reliability_rating": SourceReliabilityRating.low.value,
        "verification_status": OpportunityVerificationStatus.unverified.value,
        "freshness_interval_days": 90,
        "check_method": SourceCheckMethod.web_page.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.quarterly.value,
        "priority_level": SourcePriorityLevel.low.value,
    },
    {
        "catalog_key": "nf-catalog-regional-rural-funder",
        "source_name": "Regional rural development collaborative (illustrative)",
        "source_type": OpportunitySourceType.regional.value,
        "publisher_name": "Illustrative regional collaborative",
        "source_url": "https://example.org/nf-catalog/regional-rural",
        "description": "Placeholder for place-based rural and tribal-adjacent funding.",
        "geographic_scope_json": {"label": "multi_state", "notes": "Northern Rockies"},
        "funding_domains_json": [
            FundingDomain.economic_development.value,
            FundingDomain.food_sovereignty.value,
            FundingDomain.water.value,
        ],
        "applicant_types_json": ["tribe", "cooperative", "nonprofit"],
        "covered_states_json": ["MT", "WY", "ND"],
        "covered_regions_json": [
            {"id": "northern_rockies", "label": "Northern Rockies"}
        ],
        "covered_tribal_groups_json": None,
        "coverage_notes": "Regional collaboratives often bridge federal and local.",
        "native_relevance_notes": "High overlap with tribal land-based economies.",
        "reliability_rating": SourceReliabilityRating.medium.value,
        "verification_status": OpportunityVerificationStatus.operator_reviewed.value,
        "freshness_interval_days": 45,
        "check_method": SourceCheckMethod.partner_feed.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.irregular.value,
        "priority_level": SourcePriorityLevel.high.value,
    },
    {
        "catalog_key": "nf-catalog-philanthropic-pooled-fund",
        "source_name": "Philanthropic pooled fund announcements (illustrative)",
        "source_type": OpportunitySourceType.philanthropic_network.value,
        "publisher_name": "Illustrative funder collaborative",
        "source_url": "https://example.org/nf-catalog/pooled-fund",
        "description": "Placeholder for pooled funds and collaborative grant rounds.",
        "geographic_scope_json": {"label": "national"},
        "funding_domains_json": [
            FundingDomain.climate_resilience.value,
            FundingDomain.justice.value,
            FundingDomain.governance.value,
        ],
        "applicant_types_json": ["native_led_nonprofit", "coalition"],
        "covered_states_json": None,
        "covered_regions_json": [{"id": "national_us", "label": "United States"}],
        "covered_tribal_groups_json": None,
        "coverage_notes": "Shared due diligence may shorten timelines.",
        "native_relevance_notes": "Watch for Native-led governance criteria.",
        "reliability_rating": SourceReliabilityRating.medium.value,
        "verification_status": OpportunityVerificationStatus.trusted.value,
        "freshness_interval_days": 30,
        "check_method": SourceCheckMethod.email_newsletter.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.monthly.value,
        "priority_level": SourcePriorityLevel.high.value,
    },
    {
        "catalog_key": "nf-catalog-private-fellowship-accelerator",
        "source_name": "Private fellowship and accelerator (illustrative)",
        "source_type": OpportunitySourceType.private.value,
        "publisher_name": "Illustrative independent program operator",
        "source_url": "https://example.org/nf-catalog/private-fellowship",
        "description": "Placeholder for fellowships, prizes, and cohort accelerators.",
        "geographic_scope_json": {"label": "national"},
        "funding_domains_json": [
            FundingDomain.workforce.value,
            FundingDomain.education.value,
            FundingDomain.other.value,
        ],
        "applicant_types_json": ["individual", "startup", "nonprofit"],
        "covered_states_json": None,
        "covered_regions_json": None,
        "covered_tribal_groups_json": None,
        "coverage_notes": "Private vehicles vary widely in eligibility language.",
        "native_relevance_notes": "May include Indigenous entrepreneurship tracks.",
        "reliability_rating": SourceReliabilityRating.unknown.value,
        "verification_status": OpportunityVerificationStatus.unverified.value,
        "freshness_interval_days": 120,
        "check_method": SourceCheckMethod.manual.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.irregular.value,
        "priority_level": SourcePriorityLevel.medium.value,
    },
    {
        "catalog_key": "nf-catalog-local-economic-development",
        "source_name": "County economic development authority (illustrative)",
        "source_type": OpportunitySourceType.local.value,
        "publisher_name": "Illustrative county authority",
        "source_url": "https://example.gov/nf-catalog/county-eda",
        "description": "Placeholder for county-level ED grants and revolving loan funds.",
        "geographic_scope_json": {"label": "county", "county_fips": "00000"},
        "funding_domains_json": [
            FundingDomain.economic_development.value,
            FundingDomain.infrastructure.value,
            FundingDomain.housing.value,
        ],
        "applicant_types_json": ["local_government", "small_business", "nonprofit"],
        "covered_states_json": ["AZ"],
        "covered_regions_json": [{"id": "four_corners", "label": "Four Corners"}],
        "covered_tribal_groups_json": None,
        "coverage_notes": "County boundaries may intersect Indian Country.",
        "native_relevance_notes": "Coordinate with tribal jurisdiction overlays.",
        "reliability_rating": SourceReliabilityRating.medium.value,
        "verification_status": OpportunityVerificationStatus.unverified.value,
        "freshness_interval_days": 60,
        "check_method": SourceCheckMethod.pdf_bulletin.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.quarterly.value,
        "priority_level": SourcePriorityLevel.medium.value,
    },
    {
        "catalog_key": "nf-catalog-national-trade-association",
        "source_name": "National trade association funding bulletin (illustrative)",
        "source_type": OpportunitySourceType.other.value,
        "publisher_name": "Illustrative national association",
        "source_url": "https://example.org/nf-catalog/trade-association",
        "description": "Placeholder for association-hosted RFAs and sponsored opportunities.",
        "geographic_scope_json": {"label": "national"},
        "funding_domains_json": [
            FundingDomain.emergency_management.value,
            FundingDomain.public_safety.value,
            FundingDomain.health.value,
        ],
        "applicant_types_json": ["members_only", "public_sector_partner"],
        "covered_states_json": None,
        "covered_regions_json": [{"id": "national_us", "label": "United States"}],
        "covered_tribal_groups_json": None,
        "coverage_notes": "Membership gates may limit applicant pools.",
        "native_relevance_notes": "Tribal departments may join as affiliate members.",
        "reliability_rating": SourceReliabilityRating.low.value,
        "verification_status": OpportunityVerificationStatus.unverified.value,
        "freshness_interval_days": 90,
        "check_method": SourceCheckMethod.rss.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.monthly.value,
        "priority_level": SourcePriorityLevel.low.value,
    },
    {
        "catalog_key": "nf-catalog-federal-health-opps",
        "source_name": "Federal health programs notices (illustrative)",
        "source_type": OpportunitySourceType.federal.value,
        "publisher_name": "Illustrative federal health agency",
        "source_url": "https://example.gov/nf-catalog/federal-health",
        "description": "Second federal lane: health-focused assistance listings (catalog only).",
        "geographic_scope_json": {"label": "national"},
        "funding_domains_json": [
            FundingDomain.health.value,
            FundingDomain.public_safety.value,
        ],
        "applicant_types_json": ["tribe", "tribal_health_org"],
        "covered_states_json": None,
        "covered_regions_json": [{"id": "national_us", "label": "United States"}],
        "covered_tribal_groups_json": None,
        "coverage_notes": "Use alongside primary federal portal entry.",
        "native_relevance_notes": "IHS and tribal health compact contexts.",
        "reliability_rating": SourceReliabilityRating.high.value,
        "verification_status": OpportunityVerificationStatus.operator_reviewed.value,
        "freshness_interval_days": 14,
        "check_method": SourceCheckMethod.api.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.weekly.value,
        "priority_level": SourcePriorityLevel.critical.value,
    },
    {
        "catalog_key": "nf-catalog-state-environment-water",
        "source_name": "State environment and water infrastructure (illustrative)",
        "source_type": OpportunitySourceType.state.value,
        "publisher_name": "Illustrative state environment agency",
        "source_url": "https://example.gov/nf-catalog/state-water",
        "description": "Second state lane: water and environment recurring programs.",
        "geographic_scope_json": {"label": "single_state", "state_code": "NM"},
        "funding_domains_json": [
            FundingDomain.water.value,
            FundingDomain.climate_resilience.value,
            FundingDomain.infrastructure.value,
        ],
        "applicant_types_json": ["tribe", "utility_district", "municipality"],
        "covered_states_json": ["NM"],
        "covered_regions_json": [{"id": "southwest", "label": "Southwest"}],
        "covered_tribal_groups_json": None,
        "coverage_notes": "Water rights context may require legal review.",
        "native_relevance_notes": "Strong overlap with tribal water settlements.",
        "reliability_rating": SourceReliabilityRating.medium.value,
        "verification_status": OpportunityVerificationStatus.unverified.value,
        "freshness_interval_days": 30,
        "check_method": SourceCheckMethod.web_page.value,
        "expected_opportunity_frequency": ExpectedOpportunityFrequency.quarterly.value,
        "priority_level": SourcePriorityLevel.high.value,
    },
]
