"""Production raw payload readiness artifacts (Gate 96G).

Writes to ``artifacts/raw_payload_production_readiness/``.

Every artifact states the same eight facts, and the two that matter most are
the ones that stay false: ``production_raw_payload_store_available`` and
``production_storage_live``. The writer refuses to run if the summary carries a
phrase claiming otherwise.

The schema artifact is generated by **reading the migration file's own column
list**, not by transcribing it. A hand-copied schema drifts from the migration
the first time someone edits one and not the other.
"""

from __future__ import annotations

import ast
import csv
import io
import json
from pathlib import Path
from typing import Any

from nativeforge.services.production_raw_payload_repository_service import (
    TABLE_NAME,
    build_repository_decision,
    repository_invariant_failures,
)
from nativeforge.services.raw_payload_body_store_contract_service import (
    body_store_invariant_failures,
    build_body_store_contract,
)
from nativeforge.services.raw_payload_evidence_model_service import (
    build_payload_evidence,
)
from nativeforge.services.raw_payload_production_readiness_service import (
    REQUIRED_COMPONENTS,
    build_production_readiness,
    production_readiness_invariant_failures,
)

SCHEMA_VERSION = "nf_raw_payload_production_readiness_artifact_v1"

ARTIFACT_DIR = "artifacts/raw_payload_production_readiness"

READINESS_JSON_NAME = "production_raw_payload_storage_readiness.json"
READINESS_CSV_NAME = "production_raw_payload_storage_readiness.csv"
SCHEMA_JSON_NAME = "nf_raw_source_payloads_schema.json"
BODY_STORE_JSON_NAME = "body_store_contract.json"
SUMMARY_NAME = "production_readiness_summary.md"

MIGRATION_PATH = "alembic/versions/0028_nf_raw_source_payloads.py"

# The eight facts every artifact in this family states.
REQUIRED_DECLARATIONS: tuple[str, ...] = (
    "metadata_table_available: true",
    "body_store_configured: false",
    "production_raw_payload_store_available: false",
    "production_storage_live: false",
    "live_fetch_performed: false",
    "collectors_active: false",
    "source_monitoring_active: false",
    "live_source_coverage: false",
)

BANNED_PHRASES: tuple[str, ...] = (
    "production storage is live",
    "production storage is ready",
    "production store is available",
    "collectors active",
    "monitoring is active",
    "live coverage",
    "65% improvement",
    "improvement over",
    "bodies stored",
)

READINESS_CSV_COLUMNS = [
    "component",
    "available",
    "required_for_production",
    "detected_how",
    "metadata_table_available",
    "body_store_configured",
    "production_raw_payload_store_available",
    "production_storage_live",
    "live_fetch_performed",
    "collectors_active",
    "source_monitoring_active",
    "live_source_coverage",
]

# How each component is established. Named so a reader can check the claim
# rather than take it.
COMPONENT_DETECTION: dict[str, str] = {
    "metadata_table_available": (
        "alembic/versions/0028_nf_raw_source_payloads.py present, or the table "
        "found by SQLAlchemy inspection when a session is supplied"
    ),
    "body_store_implementation_available": (
        "s3_raw_payload_body_store_service.store_body importable and callable; "
        "the seam takes an injected client, so no SDK is required"
    ),
    "body_store_configured": (
        "all five RAW_PAYLOAD_OBJECT_STORE_* settings hold real, non-blank, "
        "non-placeholder values - read by value, never by field existence, and "
        "no credential value is rendered"
    ),
    "secret_scan_available": (
        "raw_payload_secret_scan_service.scan_payload_for_secrets importable "
        "and callable"
    ),
    "promotion_gate_available": (
        "raw_payload_promotion_gate_service.evaluate_payload_promotion "
        "importable and callable"
    ),
}


class ProductionReadinessArtifactError(RuntimeError):
    """Raised when a readiness artifact would carry a forbidden claim."""


def _json_safe(x: Any) -> Any:
    json.dumps(x)
    return x


def _rows_to_csv(rows: list[dict[str, Any]], columns: list[str]) -> str:
    buffer = io.StringIO()
    writer = csv.DictWriter(
        buffer, fieldnames=columns, extrasaction="ignore", lineterminator="\n"
    )
    writer.writeheader()
    for row in rows:
        writer.writerow(
            {
                c: (
                    ";".join(str(v) for v in row.get(c))
                    if isinstance(row.get(c), list)
                    else row.get(c)
                )
                for c in columns
            }
        )
    return buffer.getvalue()


def read_migration_schema(*, repo_root: Any = None) -> dict[str, Any]:
    """Parse 0028 and report the table it creates. Read, never transcribed."""
    root = Path(repo_root) if repo_root else Path(__file__).resolve().parents[3]
    path = root / MIGRATION_PATH
    if not path.exists():
        return {
            "migration_present": False,
            "table": TABLE_NAME,
            "columns": [],
            "indexes": [],
            "check_constraints": [],
            "unique_constraints": [],
        }

    tree = ast.parse(path.read_text(encoding="utf-8"))

    columns: list[str] = []
    checks: list[str] = []
    uniques: list[str] = []
    indexes: list[str] = []

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
            continue
        attr = node.func.attr
        if attr == "Column" and node.args:
            first = node.args[0]
            if isinstance(first, ast.Constant) and isinstance(first.value, str):
                columns.append(first.value)
        elif attr in {"CheckConstraint", "UniqueConstraint"}:
            for kw in node.keywords:
                if kw.arg == "name" and isinstance(kw.value, ast.Constant):
                    (checks if attr == "CheckConstraint" else uniques).append(
                        kw.value.value
                    )
        elif attr == "create_index" and node.args:
            first = node.args[0]
            if isinstance(first, ast.Constant) and isinstance(first.value, str):
                indexes.append(first.value)

    return {
        "migration_present": True,
        "migration_path": MIGRATION_PATH,
        "revision": "0028",
        "down_revision": "0027",
        "table": TABLE_NAME,
        "columns": columns,
        "column_count": len(columns),
        "indexes": sorted(set(indexes)),
        "check_constraints": sorted(set(checks)),
        "unique_constraints": sorted(set(uniques)),
        "stores_response_body": False,
        "body_reference_column": "raw_payload_ref",
    }


def build_readiness_bundle(*, repo_root: Any = None) -> dict[str, Any]:
    readiness = build_production_readiness()
    body_store = build_body_store_contract()
    schema = read_migration_schema(repo_root=repo_root)

    # A representative repository decision, produced by calling the real
    # repository so the artifact cannot describe behaviour the code does not
    # have.
    sample = build_payload_evidence(
        source_id="example_source",
        retrieved_at="2026-08-27T00:00:00Z",
        response_body_hash="0" * 64,
        raw_payload_ref="bodies/00/" + "0" * 64 + ".bin",
        request_fingerprint="scenario",
        secret_scan_status="clean",
        redaction_status="not_required",
        terms_status="NO_REVIEW_REQUIRED",
        parser_status="not_started",
        created_from_fixture=True,
    )
    repository = build_repository_decision(payload=sample)

    return {
        "schema_version": SCHEMA_VERSION,
        "readiness": readiness,
        "body_store": body_store,
        "schema": schema,
        "repository": repository,
    }


def artifact_claim_failures(bundle: dict[str, Any], summary_text: str) -> list[str]:
    fails: list[str] = []
    fails.extend(production_readiness_invariant_failures(bundle["readiness"]))
    fails.extend(body_store_invariant_failures(bundle["body_store"]))
    fails.extend(repository_invariant_failures(bundle["repository"]))

    schema = bundle["schema"]
    if not schema.get("migration_present"):
        fails.append("migration_0028_absent")
    if schema.get("stores_response_body") is not False:
        fails.append("schema_claimed_to_store_bodies")

    lowered = summary_text.lower()
    for phrase in BANNED_PHRASES:
        if phrase in lowered:
            fails.append(f"banned_phrase_in_summary:{phrase}")
    for declaration in REQUIRED_DECLARATIONS:
        if declaration not in lowered:
            fails.append(f"required_declaration_missing:{declaration}")

    return fails


def render_readiness_summary(bundle: dict[str, Any]) -> str:
    readiness = bundle["readiness"]
    schema = bundle["schema"]
    lines: list[str] = []
    add = lines.append

    add("# Production raw payload storage readiness")
    add("")
    add(
        "A metadata table exists. A body store does not. **Adding a table is "
        "not the same as production storage being live.**"
    )
    add("")
    add("```text")
    for declaration in REQUIRED_DECLARATIONS:
        add(declaration)
    add("```")
    add("")

    add("## Components")
    add("")
    add("| Component | Available | How it is established |")
    add("| --- | --- | --- |")
    for name in REQUIRED_COMPONENTS:
        available = "yes" if readiness[name] else "**no**"
        add(f"| `{name}` | {available} | {COMPONENT_DETECTION[name]} |")
    add("")
    add(
        f"{len(readiness['components_present'])} of "
        f"{len(REQUIRED_COMPONENTS)} present. "
        "`production_raw_payload_store_available` is derived from all four, "
        "never set beside them, so it cannot read true while one is missing."
    )
    add("")

    add("## Why the body store is missing")
    add("")
    add(
        "There is no object-store client in the dependency set and none of the "
        "three required settings exists on the Settings model. Both are "
        "checked by importing and inspecting rather than by reading a flag - a "
        "flag saying a component exists is a claim about a claim."
    )
    add("")

    add("## The migration")
    add("")
    add(
        f"`{schema.get('migration_path', MIGRATION_PATH)}` creates "
        f"`{schema['table']}` with **{schema.get('column_count', 0)} columns**, "
        f"{len(schema.get('indexes', []))} indexes, "
        f"{len(schema.get('unique_constraints', []))} unique constraint and "
        f"{len(schema.get('check_constraints', []))} check constraints."
    )
    add("")
    add(
        "It stores a content-addressed reference and the hashes needed to "
        "verify what it points at. It does not store response bodies: a 78 MB "
        "Grants.gov extract is not a database row."
    )
    add("")

    add("## Next required actions")
    add("")
    for action in readiness["next_required_actions"]:
        add(f"- {action}")
    add("")

    return "\n".join(lines) + "\n"


def write_readiness_artifacts(
    *, repo_root: Any = None, artifact_dir: str = ARTIFACT_DIR
) -> dict[str, Any]:
    root = Path(repo_root) if repo_root else Path(__file__).resolve().parents[3]

    # The schema is read from this repo's migration even when writing artifacts
    # into a temp tree, so the determinism test compares like with like.
    source_root = Path(__file__).resolve().parents[3]
    bundle = build_readiness_bundle(repo_root=source_root)
    summary_text = render_readiness_summary(bundle)

    failures = artifact_claim_failures(bundle, summary_text)
    if failures:
        raise ProductionReadinessArtifactError(
            "refusing to write production readiness artifacts: "
            + ", ".join(sorted(set(failures)))
        )

    out_dir = root / artifact_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    readiness = bundle["readiness"]
    declarations = {
        "metadata_table_available": bool(readiness["metadata_table_available"]),
        "body_store_configured": bool(readiness["body_store_configured"]),
        "production_raw_payload_store_available": bool(
            readiness["production_raw_payload_store_available"]
        ),
        "production_storage_live": bool(readiness["production_storage_live"]),
        "live_fetch_performed": False,
        "collectors_active": False,
        "source_monitoring_active": False,
        "live_source_coverage": False,
    }

    (out_dir / READINESS_JSON_NAME).write_text(
        json.dumps(
            {
                "schema_version": SCHEMA_VERSION,
                **declarations,
                "readiness": readiness,
                "component_detection": COMPONENT_DETECTION,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    rows = [
        {
            "component": name,
            "available": readiness[name],
            "required_for_production": True,
            "detected_how": COMPONENT_DETECTION[name],
            **declarations,
        }
        for name in REQUIRED_COMPONENTS
    ]
    (out_dir / READINESS_CSV_NAME).write_text(
        _rows_to_csv(rows, READINESS_CSV_COLUMNS), encoding="utf-8"
    )

    (out_dir / SCHEMA_JSON_NAME).write_text(
        json.dumps(
            {"schema_version": SCHEMA_VERSION, **declarations, **bundle["schema"]},
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    (out_dir / BODY_STORE_JSON_NAME).write_text(
        json.dumps(
            {"schema_version": SCHEMA_VERSION, **declarations, **bundle["body_store"]},
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    (out_dir / SUMMARY_NAME).write_text(summary_text, encoding="utf-8")

    return _json_safe(
        {
            "schema_version": SCHEMA_VERSION,
            "artifact_dir": artifact_dir,
            "files": [
                READINESS_JSON_NAME,
                READINESS_CSV_NAME,
                SCHEMA_JSON_NAME,
                BODY_STORE_JSON_NAME,
                SUMMARY_NAME,
            ],
            "components_present": len(readiness["components_present"]),
            "components_missing": len(readiness["components_missing"]),
            **declarations,
            "claim_failures": [],
        }
    )
